### ISSUE TITLE
Provide guidance on best setup for tail latencies when setting CPU limits

### ISSUE THREAD

**Issue by rkruze** [redpanda-data/helm-charts#10]
JIRA Link: [K8S-2](https://redpandadata.atlassian.net/browse/K8S-2)

[K8S-2]: https://redpandadata.atlassian.net/browse/K8S-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age an inactivity.
