### ISSUE TITLE
Unable to upgrade helm with enabling TS

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/helm-charts#1032]
### What happened?

* The staging environment went from helm chart version `5.3.3` to `5.7.15` . We use the default RP version for each, so this should have updated to `23.2.x` - `23.3.4` at the same time TS was enabled
* The upgrade failed because `rpk cluster config set` requires 2 parameters, and was only given
* Narrowing this down to `$CLOUD_STORAGE_SECRET_KEY` not being set, despite the key and secret being set.
* After some finagling, deleted the statefulset to try to get an entire new cluster. This also failed, because the `configurator` (now getting the storage key correctly, with no other changes), can’t run `rpk cluster config set` because there’s no cluster.
* So removed that line in the secret that stores `configurator.sh`, removed that line to get the nodes up and running (without tiered storage), then added the line back in and restarted the statefulset. That seemed to have at least got things stable.

### What did you expect to happen?

Upgrading helm along with redpanda + enabling TS should work as expected.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Posted in "What happened"

### Anything else we need to know?

https://redpandadata.slack.com/archives/C01H6JRQX1S/p1708409244454229

### Chart Version(s)

5.7.15

### Cloud provider

N/A

**Comment by chrisseto** [comment]
@daisukebe this should be fixed in the latest release: https://github.com/redpanda-data/helm-charts/releases/tag/redpanda-5.7.32

**Comment by daisukebe** [comment]
Thanks. Just linking to the corresponding fix for a reference: https://github.com/redpanda-data/helm-charts/pull/1054
