### ISSUE TITLE
Remove `add1` usage

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#113]
The `add1` function takes an integer and returns the value + 1. This is currently used in 6 places in `_helpers.tpl`, including here:

https://github.com/redpanda-data/helm-charts/blob/899400cd9fdbed3ea398d7db6d1ff78856c2bcc0/redpanda/templates/_helpers.tpl#L175

The issue is that this isn't explained to the user, and it assumes that port will be available in the user's cluster. Instead, this port should be defined in `values.yaml` and the user can then have more control over their environment's used ports.

**Comment by joejulian** [comment]
fixed in #122
