### ISSUE TITLE
🔹 Don't set duplicate CLI flags if provided by the end user

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1134]
As it stands, if a user passes in an extra CLI flag to forward to redpanda that's already specified, it will be (incorrectly) provided twice.

This is most relevant in the context of `--memory` and `--reserve-memory`. In ~some~ most cases the built in memory calculations are tedious to understand and difficult to control. Instead, we should let users specify these flags directly and rely on their values rather than trying to force them through the charts memory calculations.

**Comment by JakeSCahill** [comment]
@chrisseto do we have a full list of supported flags?

**Comment by chrisseto** [comment]
@JakeSCahill I think that would be anything that could be passed to `rpk redpanda start`?
