### ISSUE TITLE
🫐 Allow to disable internal Operator CAs: `default`, and `external` 

### ISSUE THREAD

**Issue by c4milo** [redpanda-data/helm-charts#1140]
### What would you like to be added?

We would like for the Redpanda cluster to only use our own CAs. However, we still want the operator to mount CA certs in the trust store of every listener, when using our self-signed issuer. 

### Why is this needed?

Better security posture. 

JIRA Link: [K8S-138](https://redpandadata.atlassian.net/browse/K8S-138)

[K8S-138]: https://redpandadata.atlassian.net/browse/K8S-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
I believe this is possible today and described in the docs: https://docs.redpanda.com/current/manage/kubernetes/security/tls/k-secrets/

If you believe there are missing parts here please let's discuss.

**Comment by chrisseto** [comment]
Oh boy, I think it is technically possible to make this setup work but IMO it really doesn't make sense to those familiar with PKI/TLS.

From what I'm gathering the `caEnabled` field means "There is a `ca.crt` containing a PEM encoded CA for this certificate within the secret that's referenced by `secretRef`.

If you set `caEnabled` to true and point `secretRef` to a secret that contains ca.crt, tls.crt, and tls.key you should be able to configure what you're looking for. Though there might be some issues with the client certs, I'm not 100% certain of that and I suspect that `caEnabled` might mean multiple things across the chart.

I think we could make this MUCH more clear if we removed caEnabled in favor of a `CA corev1.SecretRef`. For backwards compatibility, we can appropriately fill out the CA field if caEnabled is true.

**Comment by c4milo** [comment]
The main need here is that we can actually mount in redpanda a trust store per listener, populated with our (cloud) and customer-provided CA certs.

**Comment by c4milo** [comment]
In other words, we like the convenience of being able to pass cert-manager CAs, but also want to be able to configure truststores in Redpanda AND do not want the operator installing its own CAs.
