### ISSUE TITLE
🫐 🐛 Operator: Updating commonLabels does not seem to work

### ISSUE THREAD

**Issue by c4milo** [redpanda-data/helm-charts#1148]
### What happened?

I set `commonLabels` in my CR. And, this is what I got: 

```console
Events:
  Type     Reason         Age   From                   Message
  ----     ------         ----  ----                   -------
  Warning  UpgradeFailed  8s    HelmReleaseReconciler  Helm upgrade failed for release redpanda/redpanda-broker with chart redpanda@5.7.37: cannot patch "redpanda-broker" with kind StatefulSet: StatefulSet.apps "redpanda-broker" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

Last Helm logs:

2024-04-04T14:49:59.015708Z: Patch Certificate "redpanda-broker-external-cert" in namespace redpanda
2024-04-04T14:49:59.040968736Z: Patch Certificate "redpanda-broker-letsencrypt-cert" in namespace redpanda
2024-04-04T14:49:59.065290115Z: Patch Certificate "redpanda-broker-selfsigned-cert" in namespace redpanda
2024-04-04T14:49:59.089878374Z: Patch Issuer "redpanda-broker-default-selfsigned-issuer" in namespace redpanda
2024-04-04T14:49:59.114574913Z: Patch Issuer "redpanda-broker-default-root-issuer" in namespace redpanda
2024-04-04T14:49:59.138430334Z: Patch Issuer "redpanda-broker-external-selfsigned-issuer" in namespace redpanda
2024-04-04T14:49:59.162118997Z: Patch Issuer "redpanda-broker-external-root-issuer" in namespace redpanda
2024-04-04T14:49:59.186072298Z: Patch Issuer "redpanda-broker-letsencrypt-root-issuer" in namespace redpanda
2024-04-04T14:49:59.208640725Z: Patch Issuer "redpanda-broker-selfsigned-root-issuer" in namespace redpanda
2024-04-04T14:49:59.36309197Z: warning: Upgrade "redpanda-broker" failed: cannot patch "redpanda-broker" with kind StatefulSet: StatefulSet.apps "redpanda-broker" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
  Normal  RollbackSucceeded  6s  HelmReleaseReconciler  Helm rollback to previous release redpanda/redpanda-broker.v1 with chart redpanda@5.7.37 succeeded
```

The release got roll back by Flux as a result. 

### What did you expect to happen?

See the labels apply to my statefulset pods. 

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

by deploying a brand new cluster without setting `commonLabels`, then updating the CR to set it and re-deploying the cluster. 

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

```console
❯ helm -n redpanda list
NAME             	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART          	APP VERSION
redpanda         	redpanda 	10      	2024-04-04 10:49:54.999923 -0400 EDT  	deployed	redpanda-0.1.1 	0.1.0
redpanda-broker  	redpanda 	5       	2024-04-04 14:50:18.75075024 +0000 UTC	deployed	redpanda-5.7.37	v23.3.10
redpanda-operator	redpanda 	1       	2024-04-01 18:14:29.732128 -0400 EDT  	deployed	operator-0.4.20	v2.1.15-23.3.7

```

### Cloud provider

<details>
Azure / AKS
</details>

**Comment by RafalKorepta** [comment]
The most important line is:
```
Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

**Comment by RafalKorepta** [comment]
BTW there is special functionality that should prevent that failure https://github.com/redpanda-data/helm-charts/blob/a0b1456c2274dcf85ea70f10af9b4e1a86846c1c/charts/redpanda/templates/_statefulset.tpl#L23-L26

Maybe that problem is not coming from `StatefulSet.spec.template.metadata.labels`.

@c4milo Could you share Redpanda custom resource before update and after update?

**Comment by alejandroEsc** [comment]
I believe there is a process for this, and you have to first orphan the pods then delete the sts. Otherwise, the api will not allow you to do so.

**Comment by c4milo** [comment]
I am not sure I get why a seemingly simple operation to relabel resources
would fail like this.

*Camilo Aguilar*

Software Engineer

redpanda.com | The streaming data platform for developers

Follow us on Twitter <https://twitter.com/redpandadata> | Join our community
<https://join.slack.com/t/redpandacommunity/shared_invite/zt-ng2ze1uv-l5VMWSGQHB9gp47~kNnYGA/>

**Comment by c4milo** [comment]
Ah, interesting. I didn't know. Can you leave those out of the scope of `commonLabels`?

**Comment by alejandroEsc** [comment]
> Ah, interesting. I didn't know. Can you leave those out of the scope of `commonLabels`?

Not entirely sure what you mean. Any labels applied to sts and its pods this will occur to.

**Comment by chrisseto** [comment]
I think what camilo is suggesting makes sense to me.

We should make the statefulset label selector _not_ accept user input and only use immutable values within it. Doing so would allow this update to go through as expected and prevent any accidental foot gunning on the users behalf.

I can't really think of any reason that end users would need to control the label selector as long as it's sufficiently unique (chart name + release name should give us that).

**Comment by alejandroEsc** [comment]
> I think what camilo is suggesting makes sense to me.
> 
> We should make the statefulset label selector _not_ accept user input and only use immutable values within it. Doing so would allow this update to go through as expected and prevent any accidental foot gunning on the users behalf.
> 
> I can't really think of any reason that end users would need to control the label selector as long as it's sufficiently unique (chart name + release name should give us that).

I do not understand, let's chat in slack.

**Comment by RafalKorepta** [comment]
I think you could test a simple change in setup local-path-provisioner script https://github.com/redpanda-data/cloudv2/blob/cec154918acf04bc8fc92f7475b66a7bf67eca8d/terraform/provisioners/kubernetes-redpanda-aws/files/local-path-provisioner.yaml#L139 to change the owner.

**Comment by chrisseto** [comment]
I think @RafalKorepta's comment is on the wrong issue.

**Comment by RafalKorepta** [comment]
> I think @RafalKorepta's comment is on the wrong issue.

I agree. @alejandroEsc During our meeting you mentioned that I should post my proposal to Github issue. I picked what you send on the chat. Maybe I miss clicked and posted in wrong GH issue. Could you share which issue we were discussing?

**Comment by RafalKorepta** [comment]
I think https://github.com/redpanda-data/helm-charts/issues/1142. If I'm wrong let me know
