### ISSUE TITLE
Update testdata with the release

### ISSUE THREAD

**Issue by RafalKorepta** [redpanda-data/helm-charts#1149]
### What would you like to be added?

When release is happen the CI could auto commit changes to `charts/redpanda/testdata/` directory.

#### Reference 

https://github.com/redpanda-data/helm-charts/pull/1136/commits/1b507ff29c7cce070283e055ca460d76f1febcbb

### Why is this needed?

To not break CI when release happen.

**Comment by chrisseto** [comment]
As part of this, we'll also want to make CI trigger `go-test` whenever the redpanda or console charts change so that CI will block version bumps if we forget to update anything.

**Comment by RafalKorepta** [comment]
> Hmmm, maybe we just make go-test always run? It's pretty fast all things considered.

Yes, it is very quick with current setup.

> As part of this, we'll also want to make CI trigger go-test whenever the redpanda or console charts change so that CI will block version bumps if we forget to update anything.

It's a problem of running `helm dep build`. The changes to `Chart.lock` will be visible after official helm chart release.
