### ISSUE TITLE
Figure out how to best handle `Chart.lock`

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1166]
We currently exclude `Chart.lock` files from git as we don't want to include them in our released charts. This has caused a lot of confusion as we now have golden tests for `helm template`. We need a more robust solution that won't cause sudden diffs whenever a new version of `console` gets released.

I think what we'll want to do is check in `Chart.lock` but exclude it from helm releases via `.helmignore`. We'd also need to update the release task to run `helm dep update` to ensure we have the latest version of the console chart in use in the development versions.

**Comment by alejandroEsc** [comment]
Following prescription from @chrisseto: https://github.com/redpanda-data/helm-charts/pull/1174

**Comment by chrisseto** [comment]
Fixed by https://github.com/redpanda-data/helm-charts/pull/1174

@alejandroEsc, should we go ahead and make the same change for our other charts? We can make another issue to track those.
