### ISSUE TITLE
Run `go fmt` or `gofumpt` against go code

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1194]
We don't currently have any style enforcement of our go code. Let's start running `go fmt` or `gofumpt` within CI to enforce consistent styling and fix the occasional diff churn with all the `+gotohelm` annotations/markers.

JIRA Link: [K8S-152](https://redpandadata.atlassian.net/browse/K8S-152)

[K8S-152]: https://redpandadata.atlassian.net/browse/K8S-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
It has been a while since i made changes to our CI, would like to use this ticket as an excuse to checkout out the current changes and start contributing here. You ok with this @chrisseto ?
