### ISSUE TITLE
Allow user override of persistent volume template in Redpanda chart

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/helm-charts#1205]
### What would you like to be added?

There's no current way to provide granular settings to the PV, such as the `reclaimPolicy`.

### Why is this needed?

It's possible a user may need to override a default defined by a `StorageClass`.

JIRA Link: [K8S-157](https://redpandadata.atlassian.net/browse/K8S-157)

[K8S-157]: https://redpandadata.atlassian.net/browse/K8S-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
AFAIK there's no way to set the `reclaimPolicy` on a PVC Template. It can only be set via the provisioner or the storage class.

Please re-open if I'm mistaken.
