### ISSUE TITLE
Running tests with chart-testing lead to flaky results

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#124]
Using `helm test...` seems to always have expected results, but `ct install...` results in failing tests regularly. Re-running the same test will likely pass. This is especially a pain since this is the tool used in github actions. Maybe upgrading to a more recent version will help, as there has been some progress on ticket resolution in the project.

https://github.com/helm/chart-testing

**Comment by joejulian** [comment]
I've run many tests with 2.0.0 with no flakiness. Closing this but please feel free to re-open if the problem returns.
