### ISSUE TITLE
Add Redpanda/helm compatibility matrix

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#126]
This includes testing with each version that has major differences to ensure compatibility, and then list any issues in the new compatibility section

**Comment by RafalKorepta** [comment]
We have that. Please take a look at 

- https://github.com/redpanda-data/helm-charts/blob/main/.github/workflows/nightly_redpanda_tip.yaml
- https://github.com/redpanda-data/helm-charts/blob/025438673e8d1aaa88696ecd7376b9e4190172f9/.github/workflows/nightly.yaml#L50-L51

So we are testing latest from dev branch, 23.2.x and 23.1.x

If that's not enough please reopen that issue.
