### ISSUE TITLE
Install cert-manager as subchart dependency

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#128]
More details here https://cert-manager.io/docs/installation/helm/#installing-cert-manager-as-subchart

**Comment by vuldin** [comment]
We discussed this internally and it seems like adding cert-manager as a subchart could introduce more problems than what it solves. Cert-manager could already be installed for one.

**Comment by EvanCarroll** [comment]
I would like to know what factors led you to this? Even if it was installed, wouldn't you want the option to version it?

Also makes it difficult to list redpanda as a dependency in our own chart, because now we have to tell users to explicitly install cert-manager.
