### ISSUE TITLE
Ensure certificate cycling works

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#129]
Redpanda should be able to do cert hotswapping without downtime, but needs to be investigated when doing so within a kubernetes environment using helm. Consider running the rpk command, modifying the data in the mounted volume where the certs live.

**Comment by alejandroEsc** [comment]
Are we assuming here that cert-manager does the replacement or are we assuming a new feature were the user will have a certificate in a secret? What are the requirements?

**Comment by RafalKorepta** [comment]
I wouldn't assume cert-manager. We are mounting Kubernetes Secret to Redpanda Pod. Kubernetes Secrets can be hot swapped. It will destroy the symlink and recreated the symlink which will point to new cert. 

P.S. https://ahmet.im/blog/kubernetes-inotify/

**Comment by alejandroEsc** [comment]
> I wouldn't assume cert-manager. We are mounting Kubernetes Secret to Redpanda Pod. Kubernetes Secrets can be hot swapped. It will destroy the symlink and recreated the symlink which will point to new cert.
> 
> P.S. https://ahmet.im/blog/kubernetes-inotify/
> 
> P.S. I would estimate around 2

These conversations made me think that we should not have to do a thing, this should then be bumped to core and their handling of changes to files.

**Comment by joejulian** [comment]
This is not something we need to test. This is an established behavior of Kubernetes and is well tested upstream.
