### ISSUE TITLE
Allow setting a port within the "image.repository" value

### ISSUE THREAD

**Issue by gspadotto** [redpanda-data/helm-charts#1292]
### What happened?

With the [current schema regex](https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/values.schema.json#L336) on "image.repository" it is not possible to use Image Registries exposed through ports.

Please add the ":" char to the set of allowed entries.

### What did you expect to happen?

It should be possible to use any port within "image.repository"

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Check [this issue](https://github.com/redpanda-data/helm-charts/issues/895). 

### Anything else we need to know?

There's a [pull request](https://github.com/helm/helm/pull/12743) for this in upstream Helm, but the change in the schema definition is quicker to apply. 

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

JIRA Link: [K8S-226](https://redpandadata.atlassian.net/browse/K8S-226)

**Comment by chrisseto** [comment]
I was expected the pattern to be a lot more complicated 😅 We'll toss this into the next release!

**Comment by gspadotto** [comment]
Hi @chrisseto thanks. 
Any rough estimate of when the next release of the chart will be available? Days? Weeks?

**Comment by chrisseto** [comment]
Pretty sure we can get this out before EOW. The PR is up and pushing out a release takes all of ~15m.
