### ISSUE TITLE
Ensure PodDisruptionBudget is configured properly

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#130]
I started a 3-node cluster, introduced an problematic parameter value in `values.yaml`, ran `helm upgrade...`, and the first node went down and failed to start properly. With 1 node down, the statefulset then brought down the 2nd node (which also failed in the same way). I expected only 1 node to be taken down due to this in `values.yaml`:
```yaml
statefulset:
  budget:
    maxUnavailable: 1
```

The value above gets used in the PodDisruptionBudget. I also see a warning in the logs:
```
52m         Warning   CalculateExpectedPodCountFailed   poddisruptionbudget/redpanda   Failed to calculate the number of expected pods: statefulsets.apps does not implement 
the scale subresource
```

**Comment by joejulian** [comment]
This was due to not having readiness checks. This should be solved. Please reopen if this problem is encountered again.
