### ISSUE TITLE
Setting container memory ignores actual available memory on the host VM

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#133]
I have been setting my container memory to be 2.5Gi, and now realize that by default minikube gives only 2200MB to each node (in a 4-node cluster, 3 worker nodes).

Attempting to set container memory to anything above the host VM's total memory (or possibly even 90% of this value) should result in at least a warning if not error and a failure to deploy.

**Comment by vuldin** [comment]
Minikube command I'm now using:
```
minikube start -n 4 --memory=3000m --extra-config=apiserver.service-node-port-range=8081-65535
```

**Comment by joejulian** [comment]
There's no way for the chart to know what node the pods will get scheduled on and test that node. This should be handled in documentation.

**Comment by RafalKorepta** [comment]
I agree with @joejulian it might require short explanation in our docs.

**Comment by JakeSCahill** [comment]
I believe this is covered in the prerequisites here: https://docs.redpanda.com/current/manage/kubernetes/manage-resources/#prerequisites

@RafalKorepta could you confirm?

**Comment by RafalKorepta** [comment]
Yes, @JakeSCahill thank you.

@vuldin if you would like to see something different please reopen this issue or open documentation issue.
