### ISSUE TITLE
Using a non-default `image.repository` results in an incorrectly generated `redpanda.yaml`

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/helm-charts#1334]
### What happened?

User is reporting that they're getting the following error from core redpanda when trying to use the 5.7.41 charts. They're running ~23.2.8~ 23.2.28 and trying to work through two separate upgrade flows, one for redpanda and one for the charts.

```
ERROR 2024-06-03 18:15:04,707 [shard 0] main - application.cc:389 - Failure during startup: std::invalid_argument (Unknown property audit_enabled)
```

Best guess is that the audit support check is incorrectly passing audit_enabled=false into the redpanda.yaml for versions lower than 23.3.0.

https://github.com/redpanda-data/helm-charts/blob/49f4661c41f97a275c4579ef9faded84217c2dc9/charts/redpanda/templates/_configmap.tpl#L130-L132

### What did you expect to happen?

Chart should not pass `audit_enabled: false` to redpanda.yaml as that causes redpanda to choke on startup.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Run 23.2.x image of redpanda with 5.7.41 (and possibly earlier).

### Which are the affected charts?

Redpanda

### Chart Version(s)

5.7.41

### Cloud provider

N/A - Self-hosted kubernetes.

JIRA Link: [K8S-249](https://redpandadata.atlassian.net/browse/K8S-249)

[K8S-249]: https://redpandadata.atlassian.net/browse/K8S-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hcoyote** [comment]
also @chrisseto

**Comment by hcoyote** [comment]
Might also be coming from here. 

https://github.com/redpanda-data/helm-charts/blob/49f4661c41f97a275c4579ef9faded84217c2dc9/charts/redpanda/templates/_configmap.tpl#L226

It's not clear though, user pointed out that either of those appear to be inside the 23-3-0 if/then block, so wanted to call it out specifically

**Comment by RafalKorepta** [comment]
Using the following check I can fairly confidently state that helm chart is working as expected.
```
$ helm repo add redpanda https://charts.redpanda.com
$ helm template redpanda redpanda/redpanda --version=5.7.41 --dry-run=client --kube-version=v1.21.0 --debug --set=image.tag=v23.2.28 | grep audit_enabled
install.go:214: [debug] Original chart version: "5.7.41"
install.go:231: [debug] CHART PATH: /Users/rafalkorepta/Library/Caches/helm/repository/redpanda-5.7.41.tgz

$ helm template redpanda redpanda/redpanda --version=5.8.7 --dry-run=client --kube-version=v1.21.0 --debug --set=image.tag=v23.2.28 | grep audit_enabled
install.go:214: [debug] Original chart version: "5.8.7"
install.go:231: [debug] CHART PATH: /Users/rafalkorepta/Library/Caches/helm/repository/redpanda-5.8.7.tgz

$ # With new image.tag that is `v23.3.2` it is working as expected.
$ helm template redpanda redpanda/redpanda --version=5.8.7 --dry-run=client --kube-version=v1.21.0 --debug --set=image.tag=v23.3.2 | grep audit_enabled
install.go:214: [debug] Original chart version: "5.8.7"
install.go:231: [debug] CHART PATH: /Users/rafalkorepta/Library/Caches/helm/repository/redpanda-5.8.7.tgz

    audit_enabled: false
      audit_enabled: false
```

Can user, that is templating Redpanda helm chart, specify `image.tag` version as overwrite of the default value?

P.S.

The audit logging was introduced in https://github.com/redpanda-data/helm-charts/pull/934.

Without image.tag value overwrite it would be enabled starting from 5.7.3 version of the Redpanda helm chart.
```
$ helm repo add redpanda https://charts.redpanda.com
$ helm template redpanda redpanda/redpanda --version=5.7.2 --dry-run=client --kube-version=v1.21.0 --debug | grep audit_enabled
install.go:214: [debug] Original chart version: "5.7.2"
install.go:231: [debug] CHART PATH: /Users/rafalkorepta/Library/Caches/helm/repository/redpanda-5.7.2.tgz

$ helm template redpanda redpanda/redpanda --version=5.7.3 --dry-run=client --kube-version=v1.21.0 --debug | grep audit_enabled
install.go:214: [debug] Original chart version: "5.7.3"
install.go:231: [debug] CHART PATH: /Users/rafalkorepta/Library/Caches/helm/repository/redpanda-5.7.3.tgz

    audit_enabled: false
      audit_enabled: false
```

**Comment by hcoyote** [comment]
the version check seems to depend on us having the default RP image repo configured. user in this case is working with a local image.repository so the version check is not resolving right because (for some unknown historical reason), we treat only our tagged versions as trusted.

**Comment by chrisseto** [comment]
I'm hesitant to just rip out the image check all at once because the blast radius could be quite large. (It'll significantly change the generation for a given input.)

Instead I think we'll have a smoother/safer experience if we add a new field that is explicitly the redpanda version, redpanda compatibility version, or something of that nature. We can have that field fallback to attempting to parse the version from the provided image tag. If that doesn't work, we'll fail the chart generation and ask the user to explicitly provide the version.
