### ISSUE TITLE
Expand on CONTRIBUTING doc

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#134]
Guidelines from Github: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

JIRA Link: [K8S-13](https://redpandadata.atlassian.net/browse/K8S-13)

[K8S-13]: https://redpandadata.atlassian.net/browse/K8S-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
