### ISSUE TITLE
"This chart is deprecated" when using helm v2 chart

### ISSUE THREAD

**Issue by ErlendFax** [redpanda-data/helm-charts#135]
I'm using the not-yet-released helm v2 chart and getting `WARNING: This chart is deprecated` when installing and upgrading.

I know it's not released yet but looking at the [project page](https://github.com/redpanda-data/helm-charts/projects/1) it seems like it's close to release so just wanted to point it out.

**Comment by joejulian** [comment]
I'm not seeing that and the Chart.yaml doesn't mark it as deprecated. Is that still happening with #143 ?

**Comment by ErlendFax** [comment]
I hadn't pulled latest, all good now. Not tried #143 yet. 

Sorry, about that. Just wanted to help.
