### ISSUE TITLE
Set up a chart repository

### ISSUE THREAD

**Issue by BenPope** [redpanda-data/helm-charts#14]
A [chart repository](https://helm.sh/docs/topics/chart_repository/) makes installation easier.

For example, it can be hosted on github pages, using with a [github action](https://github.com/marketplace/actions/helm-chart-releaser).

**Comment by vuldin** [comment]
Also see details on helm support for storing charts in OCI registries (adding in v3.8): https://helm.sh/blog/storing-charts-in-oci/

**Comment by oskapt** [comment]
Storing charts in OCI registries is interesting, but it's not a common use case for public charts. It also breaks searching (see the Limitations section on the page you referenced). 

People expect to add a Helm repo as an HTTP endpoint. If we're concerned about where to put this and who maintains the infra, GH Pages might be a nice compromise.

**Comment by vuldin** [comment]
@jrkinley asked about this issue and posted the following link in slack: https://harness.io/blog/helm-chart-repo
