### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#147]
_There was a [previous ticket](https://github.com/redpanda-data/helm-charts/issues/122) to track creating a release, but it ended up being related to merging v2 branch into main._

Now that v2 branch is merged into main we should create a v2 release (to be listed [here](https://github.com/redpanda-data/helm-charts/releases) of the helm chart. This will be the first step towards publishing the chart in the helm repo (see https://github.com/redpanda-data/helm-charts/issues/14).

**Comment by vuldin** [comment]
Link to draft release: https://github.com/redpanda-data/helm-charts/releases/tag/untagged-ff272f19a26e5fd85189

**Comment by joejulian** [comment]
done

**Comment by vuldin** [comment]
There is currently only a draft release for v2, this should be taken out of draft or updated?

**Comment by joejulian** [comment]
We're not using GitHub releases. They don't make sense for helm chart repos as the charts in the repo are all different versions.

More charts are coming.
