### ISSUE TITLE
Docs mention starting 3 worker nodes, kind config shows 4

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#148]
This is a minor difference between what is said in docs: https://github.com/redpanda-data/helm-charts/blob/main/README.md?plain=1#L62-L79

And what is given in the new kind config: https://github.com/redpanda-data/helm-charts/blob/main/.github/kind.yaml

At the same time, the kind config here may be different than what the user would use. But it may make sense for these to match or to explain how the config file is used.

**Comment by joejulian** [comment]
This is only used for testing because the ct testing installs 4 1-node redpanda clusters and tests them in parallel. Fewer workers cause the tests to fail because they can't get scheduled.
