### ISSUE TITLE
operator: allow setting security context on the deployment

### ISSUE THREAD

**Issue by chrisseto** [redpanda-data/helm-charts#1487]
The operator's chart does not currently allow setting either the Pod nor container security contexts. While this can be worked around with a Kustomize post-render step, it would be ideal to support this directly in the chart itself.

JIRA Link: [K8S-316](https://redpandadata.atlassian.net/browse/K8S-316)

**Comment by RafalKorepta** [comment]
It should be possible to set security context in operator helm chart version 0.4.29

Example of usage:
https://github.com/redpanda-data/helm-charts/blob/182bd51aeaaf2c53a86d9b5fd39a92be48ea5689/charts/operator/testdata/template-cases.txtar#L11-L31
