### ISSUE TITLE
support prometheus servicemonitors

### ISSUE THREAD

**Issue by ekovacs** [redpanda-data/helm-charts#149]
it would be great if the chart would support servicemonitors for prometheus.
this would involve two things:

- create a service monitor template
- add back the `admin` port in the `service.internal.yaml` as the servicemonitor targets `/metrics` path at the admin port

**Comment by ekovacs** [comment]
meanwhile/until this is resolved, we are patching the service after creation/deploy to add the needed port for the `ServiceMonitor`

**Comment by joejulian** [comment]
If you have a template that you already use, please consider opening a PR.

**Comment by prune998** [comment]
just created https://github.com/redpanda-data/helm-charts/pull/498 thats is exaclty that !
