### ISSUE TITLE
`helm template` fails for redpanda chart

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#1520]
### What happened?

In the charts/redpanda directory:
```
helm template .
```
produces
```
Error: template: redpanda/templates/tests/test-console.yaml:45:144: executing "redpanda/templates/tests/test-console.yaml" at <include "console.ContainerPort" (dict "a" (list (dict "Values" (dict "AsMap" .Values.console))))>: error calling include: template: no template "console.ContainerPort" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

### What did you expect to happen?

I expected the defaults to produce a working set of kubernetes resources.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
git clone https://github.com/redpanda-data/helm-charts
cd helm-charts/charts/redpanda
helm template .
Error: template: redpanda/templates/tests/test-console.yaml:45:144: executing "redpanda/templates/tests/test-console.yaml" at <include "console.ContainerPort" (dict "a" (list (dict "Values" (dict "AsMap" .Values.console))))>: error calling include: template: no template "console.ContainerPort" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

git commit 182bd51a

### Cloud provider

<details>
N/A
</details>

JIRA Link: [K8S-353](https://redpandadata.atlassian.net/browse/K8S-353)

**Comment by chrisseto** [comment]
Have you run `helm dep build`? `helm template .` works at that commit for me, even after running `git clean -xdf`.

**Comment by joejulian** [comment]
:facepalm:
