### ISSUE TITLE
Issue applying license key

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#154]
A user reported that adding a license key doesn't work as expected. They set `.Values.license_key` and verified that this makes it into `redpanda.yaml`, but once the cluster is up it doesn't detect the license:

```shell
> rpk cluster license info
this cluster is missing a license
```

**Comment by vuldin** [comment]
We may need to set the license with `rpk cluster license set` in a post-install script.

**Comment by vuldin** [comment]
Related: https://github.com/redpanda-data/redpanda/pull/5223

**Comment by joejulian** [comment]
> They set `.Values.license_key`
They should have set `license_key`.

**Comment by joejulian** [comment]
Never mind that. I see you said it makes it into `redpanda.yaml`. I wonder if it should be in `.bootstrap.yaml`

**Comment by vuldin** [comment]
It seems that this needs to be set with `rpk cluster license set...` command. More details on how to use this command from the help output:
```
> rpk help cluster license set
Upload license to the cluster

You can either provide a path to a file containing the license:

    rpk cluster license set --path /home/organization/redpanda.license

Or inline the license string:

    rpk cluster license set <license string>

If neither are present, rpk will look for the license in the
default location '/etc/redpanda/redpanda.license'.
...
```
