### ISSUE TITLE
How do you disable external access?

### ISSUE THREAD

**Issue by soudaburger** [redpanda-data/helm-charts#159]
I see numerous PRs and support for explicitly enabling external access.  In my case, I explicitly do NOT want this.

Setting `external.enabled: false` does not globally disable external configuration.  What is the proper values configuration for disabling external access? If I disable the above, the `external-nodeport-enabled` template still iterates over the listeners.  I don't think it should be doing this? If it should still be doing this, what is the proper listener configuration to disable external configuration?

**Comment by joejulian** [comment]
```
$ helm template rp . -s templates/services.nodeport.yaml --set external.enabled=false                                #
---
# Source: redpanda/templates/services.nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: rp-external
  namespace: "default"
  labels:
    helm.sh/chart: redpanda-2.1.1
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "rp"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/component: redpanda
spec:
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: None
  ports:
  selector:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "rp"
```
lists no ports, so it's not exposing anything. It does appear to be a bug that it's even producing the Service resource at all though.

**Comment by joejulian** [comment]
@soudaburger would you have some time to test this and add your :heavy_check_mark: ? https://github.com/redpanda-data/helm-charts/pull/163
