### ISSUE TITLE
Default of 3GB on Storage is causing producing issues

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/helm-charts#167]
Right now, the storage is set to 3GB and that's causing producers to fail with defaults. With full disk handling in our latest release, it is defaulted to 5GB so with 3GB, people won't be able to produce until they change the min free bytes to something lower.

We may want a note either in comments or README about how to run locally vs how to go to production vs how to install in EKS for development purposes, etc.

Also, Overprovisioned is set to false which should probably be True for local development, so in general I think we need to clean up defaults and make them consistent all the way around. We can start with specific defaults for an assumed most common mode and document that, and then give new defaults for different modes.

**Comment by joejulian** [comment]
We'd like to go the other way around and make the defaults production ready (for some definition of "production") and document/example development configuration.

**Comment by joejulian** [comment]
Fixed in #180
