### ISSUE TITLE
Add self-signed TLS example

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#185]
This page is still the placeholder and needs to be expanded on: https://github.com/redpanda-data/helm-charts/tree/main/examples/with-selfsigned-tls

**Comment by vuldin** [comment]
Two possibilities are to 1) remove the repo placeholder README or 2) add a link to the existing doc to the repo placeholder README.

Link to docs: https://docs.redpanda.com/docs/security/kubernetes-tls/

**Comment by andreyolv** [comment]
Page Not Found

**Comment by vuldin** [comment]
Hmm, I see the link has been changed to the following: https://docs.redpanda.com/docs/manage/kubernetes/security/kubernetes-tls/

But the original also redirects to that new link for me automatically. Maybe the redirect was still being generated or something when you first tried? Let me know if the link original link redirects for you.

**Comment by RafalKorepta** [comment]
@vuldin if you feel there needs to be something more added to the docs please open new issue in docs repo.
