### ISSUE TITLE
`PodDisruptionBudget` resource should be optional - it now prevents deployment on K8s 1.20 and below

### ISSUE THREAD

**Issue by vovtz** [redpanda-data/helm-charts#187]
The template for the `PodDisruptionBudget` should only render if its resource type is available on the cluster.

**Comment by joejulian** [comment]
Also asked in the PR:
> The PDB is critical to prevent outages, split brain, and data loss. I think we should just prevent the chart from being used on k8s < 1.21 (which was merged before I saw this issue/PR). What do you think?

**Comment by vovtz** [comment]
For our current use case there is no HA requirement, we plan to use Redpanda only to create ephemeral one-node ‘clusters’ that are used in component testing. In future we might decide to use Redpanda in production too, but for now we use Kafka.

(BTW, we obviously shouldn’t run K8s versions that are EOL anyway - we urgently requested to upgrade.)
