### ISSUE TITLE
tls.certs.default.issuerRef expects string, not object

### ISSUE THREAD

**Issue by nerok** [redpanda-data/helm-charts#193]
I tried to follow the guide here: https://docs.redpanda.com/docs/platform/security/kubernetes-tls/#use-custom-issuer
But as stated in the title this fails with the message "tls.certs.default.issuerRef: Invalid type. Expected: string, given: object". I have tried passing in the content as a string, using either "issuerRef: |" or just quotation marks around name and kind. After looking at `values.schema.json` I would guess that the issue is that you have the wrong type there. If that is not the case another example of how to use custom issuer would likely be needed.

I am trying to install this helm chart using Ranchers applications: https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps

**Comment by vuldin** [comment]
Thanks for the report @nerok ! It does look to be an issue with the issuerRef type in `values.schema.json` at first glance. I'll take a closer look and get it resolved.

**Comment by carlreid** [comment]
Just hit this too; is there any workaround currently?

**Comment by vuldin** [comment]
Yep thanks for both the PR and for mentioning it here @carlreid . I do expect that PR resolved this ticket, so @nerok post your results when using the latest from main branch.

**Comment by joejulian** [comment]
Tested this. Custom issuers works correctly now.
