### ISSUE TITLE
Question: Does the chart support mTLS for client AuthN?

### ISSUE THREAD

**Issue by vovtz** [redpanda-data/helm-charts#200]
Am I right in presuming the current Helm chart has no support for using client certificates for authentication, instead of _SASL_? I seem to understand from the _Redpanda_ documentation that `authentication_method` in the server config (my guess is it would need to be added below https://github.com/redpanda-data/helm-charts/blob/main/redpanda/templates/configmap.yaml#L101) should be set to `tls` for that.

**Comment by joejulian** [comment]
Correct, this is a feature that's high on my priority list and is covered by https://github.com/redpanda-data/helm-charts/issues/65

**Comment by joejulian** [comment]
Closing as a duplicate. Will track in #65
