### ISSUE TITLE
Add dnsTrailingDotDisabled options like in operator

### ISSUE THREAD

**Issue by ThinkBriK** [redpanda-data/helm-charts#218]
In the redpanda operator you can use `dnsTrailingDotDisabled` to disable the trailing dot in the advertised address to Kafka clients.
Please port this option to the helm chart to allow java kafka client connections over https (as it prevents https certificate validation).

**Comment by joejulian** [comment]
That seems like a security risk. Wouldn't it be better to add the trailing dot to the SAN?

The better flag, imho, would be one to remove the ambiguous SANs.
mycluster-0.mynamespace.svc.cluster.local also matches `[mycluster-0.mynamespace.svc.cluster.local.stealyourdata.com](http://mycluster-0.mynamespace.svc.cluster.local.stealyourdata.com/). but mycluster-0.mynamespace.svc.cluster.local. is fully qualified and cannot be spoofed.

WDYT?
