### ISSUE TITLE
Remove environment variables from named templates

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#223]
Looking at a few named templates, I see they are using environment variables to allow the container to replace the text with the actual value (`SERVICE_NAME` or `HOST_IP`): https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/_helpers.tpl#L115-L141

It looks like the above link doesn't include all templates with this description. I think using environment variables in templates is an issue because that means these will only work within files that spin up containers (that's the only time when the variables exist). We don't mention that or block their use anywhere else (in fact it probably isn't possible to do so). I know in the past I've mistakenly tried to use these named templates in ConfigMap or other places and found that the environment variable being referenced is just passed through without ever being associated tothe expected value.

I think these named templates should be removed to avoid this confusion, or possibly handled differently so that the chance for confusion is much less. I'll create an issue around this and hopefully that can be handled in a separate PR.

**Comment by joejulian** [comment]
Fixed in #220
