### ISSUE TITLE
Do `ct install` tests for console.

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#236]
Do `ct install` tests for console.

JIRA Link: [K8S-18](https://redpandadata.atlassian.net/browse/K8S-18)

[K8S-18]: https://redpandadata.atlassian.net/browse/K8S-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
