### ISSUE TITLE
Liveness probe fails for a pod during install, unable to reach port 9644

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#248]
A community user posted about this [here](https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1671265628594829?thread_ts=1671213179.436399&cid=C01AJDUT88N).

The events on the failing pod:
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Normal   Pulled     27m (x283 over 15h)    kubelet  Container image "vectorized/redpanda:v22.3.3" already present on machine
  Warning  Unhealthy  7m12s (x868 over 15h)  kubelet  Liveness probe failed: *   Trying ::1:9644...
* connect to ::1 port 9644 failed: Connection refused
*   Trying 127.0.0.1:9644...
* connect to 127.0.0.1 port 9644 failed: Connection refused
* Failed to connect to localhost port 9644: Connection refused
* Closing connection 0
  Warning  BackOff  2m11s (x3697 over 15h)  kubelet  Back-off restarting failed container
```

The pod ends up being in state `CrashLoopBackOff`. Deleting and having the pod be replaced by the statefulset did not solve the issue, but deleting the namespace and re-installing did.

I've seen this exact same behavior sporadically, so it's seems like some issue either with the order resources get started or some timeout issue.

**Comment by vuldin** [comment]
I'm having trouble reproducing this. When anyone runs into this bug, it will be important to get logs from the failing pod. Replace `redpanda-0` in the command below with the failing pod, then attach `issue248-log.txt` to this issue:
```
kubectl logs -n redpanda -c redpanda redpanda-0 > issue248-log.txt
```

**Comment by doganyazar** [comment]
It happened again on my cluster. Attaching the logs for the crashing pod.
[redpanda-0.txt](https://github.com/redpanda-data/helm-charts/files/10261826/redpanda-0.txt)

**Comment by vuldin** [comment]
Thanks for those very helpful logs. Do you also have the `helm install` command you used? And if you use a custom `values.yaml` file that would also be helpful.

**Comment by doganyazar** [comment]
Sure. I am running chart version 2.3.1 and app version 22.3.3.
`helm upgrade --install --dry-run --debug -f values.yaml redpanda redpanda/redpanda`
[values.yaml.txt](https://github.com/redpanda-data/helm-charts/files/10268754/values.yaml.txt)

**Comment by doganyazar** [comment]
I have run into it again on another cluster but this time I enabled trace logs. It looks like there is some compatibility issues (rpc parsing issues). Attaching the log.
[redpanda-1-trace.txt](https://github.com/redpanda-data/helm-charts/files/10277916/redpanda-1-trace.txt)

**Comment by vuldin** [comment]
@doganyazar It looks like I've replicated the issue locally and am looking into it now.

**Comment by andrwng** [comment]
@doganyazar can you also include trace logs from the other two nodes in the cluster?

**Comment by doganyazar** [comment]
@andrwng Sure, attaching the latest logs from both. They are a bit big so had to zip them. 
[redpanda-logs-0-2.zip](https://github.com/redpanda-data/helm-charts/files/10284552/redpanda-logs-0-2.zip)

**Comment by andrwng** [comment]
Thanks @doganyazar!

I think the biggest clues from those logs are (from redpanda-2):

```
DEBUG 2022-12-22 06:55:53,758 [shard 0] rpc - transport.cc:265 - could not parse header from server: {host: redpanda-1.redpanda.edge.svc.cluster.local., port: 33145}
...
DEBUG 2022-12-22 06:55:54,684 [shard 0] r/heartbeat - heartbeat_manager.cc:281 - Received error when sending heartbeats to node 1 - rpc::errc::unknown
```

where it looks like messages are getting garbled up at the RPC layer. It does look like they're able to send bytes over the wire though. Not sure if it'd be relevant but is TLS enabled on this cluster?

**Comment by doganyazar** [comment]
TLS is enabled on Ingress but as far as I know it does not affect the communication between redpanda nodes. 

By the way I have noticed something that is probably worth mentioning to lay out the full picture. We have init containers that create the metrics using rpk against the cluster (using commands `rpk topic create [topic]` and `rpk topic list`) and these init containers were using a previous redpanda image version: v22.2.4 but cluster is on v22.3.3.

**Comment by joejulian** [comment]
@vuldin You mentioned having a repro. Did you get anywhere on this or did it get lost over the holiday break?

**Comment by joejulian** [comment]
I asked Josh about this. The answer is that he was looking at another issue that looked similar and he thought the repro was for this. He realized later that it was a different issue making his potential repro irrelevant.

That said, there have been a lot of stability changes around this in the last two months. I'm going to close this but if it's still an issue with the latest chart, please ping me and I'll reopen it.
