### ISSUE TITLE
Allow setting free space threshold alert within helm chart

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#249]
Running the following command on a running cluster sets this value:
```
rpk cluster config set storage_space_alert_free_threshold_percent 10
```

This could be set from the helm chart during the install process and then made visible within `values.yaml`.

**Comment by RafalKorepta** [comment]
@vuldin Could you explain what is the ask? As far as I can understand today you can set https://docs.redpanda.com/current/reference/tunable-properties/#storage_space_alert_free_threshold_percent in [tunable section of the values.yaml](https://github.com/redpanda-data/helm-charts/blob/3673e47e7598aae4545785185742a9bd746119ea/charts/redpanda/values.yaml#L916). 

I don't think rpk team would like to include helm values changes in ConfigMap or in Secret.

**Comment by vuldin** [comment]
Yep you are right @RafalKorepta, this ticket can be closed as this parameter can be set within values.yaml
