### ISSUE TITLE
Detect when helm has `debug` flag, and enable Redpanda debug logging for specific subsystems

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#251]
The following command would enable debug logging in Redpanda:
```
helm install --install --debug redpanda redpanda/redpanda
```

Not sure which subsystems would be most appropriate to enable debug logging for, but definitely `cluster`. We can work out a list.

**Comment by joejulian** [comment]
This is not possible. The debug flag is not exposed to the templates.
