### ISSUE TITLE
Post deploy health check comes back too quickly

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/helm-charts#261]
A lot of the jobs don't wait for the cluster to be full up and running. It would be great to have a retry loop (or something) to absolutely ensure that the cluster is *actually* up.  User has found himself having to redeploy to fully check status and that's not best practice.

**Comment by alejandroEsc** [comment]
This may be more of an issue with Helm, for now we recommend using the `--wait` flag for deployment. We will update this ticket as we come up with other solutions or the helm issues gets resolved. 

@joejulian submitted this issue: https://github.com/helm/helm/issues/11778

**Comment by joejulian** [comment]
Also note the instruction after the helm install has completed:

```
kubectl -n <namespace> rollout status statefulset <release name> --watch
```

Between the above instruction from the install output, and the documentation stating to use the wait flag, I'm going to go ahead and close this as complete.
