### ISSUE TITLE
Improve rack awareness label discovery

### ISSUE THREAD

**Issue by marekm-gain** [redpanda-data/helm-charts#263]
Hello,

in our environment we are using taints on nodes with the same name as rack label. This is breaking this piece of code: https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/statefulset.yaml#L140
`RACK=$(curl --silent --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt --fail -H 'Authorization: Bearer '$(cat /run/secrets/kubernetes.io/serviceaccount/token) "https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}/api/v1/nodes/${KUBERNETES_NODE_NAME}?pretty=true" | grep {{ .Values.rackAwareness.nodeAnnotation | quote | squote }} | grep -v '\"key\":' | sed 's/.*": "\([^"]\+\).*/\1/')`

As a workaround we have added additional grep:
`.... | grep {{ .Values.rackAwareness.nodeAnnotation | quote | squote }} | grep -v '\"key\":' | sed 's/.*": "\([^"]\+\).*/\1/'`

It would be better to do it using for example jq but it would need to be added to the image.

**Comment by joejulian** [comment]
Agree, though not jq and all the python that comes with it. Gojq would be good though.

Any interest in opening a PR with that grep change and getting your name in the contributors list?

**Comment by burandobata** [comment]
Thanks, PR with workaround created.

**Comment by burandobata** [comment]
I've singed CLA but it is still pending. I think I had same issue last time when I've done some commits here (I don't think it was ever applied for me).

<img width="831" alt="Screenshot 2023-01-12 at 10 21 47" src="https://user-images.githubusercontent.com/34664543/212029786-42f80f1d-f7d2-4454-b7de-23a107050acf.png">

**Comment by burandobata** [comment]
<img width="1045" alt="Screenshot 2023-01-12 at 15 30 24" src="https://user-images.githubusercontent.com/34664543/212094915-02285383-d4ff-44eb-95df-a837967ee9d5.png">
