### ISSUE TITLE
Create role with read permissions for a service account for `rpk debug bundle`

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/helm-charts#270]
Part of K8S rpk debug bundle epic: https://github.com/redpanda-data/redpanda/issues/5081

We need a **ClusterRole** to read node data, and that **ClusterRole** must be attached to a **ServiceAccount** which we can use when running `rpk debug bundle` inside the pod and be able to gather resources in the redpanda namespace.

This would be a similar configuration technique to the one used for enabling rack awareness: https://github.com/redpanda-data/helm-charts/commit/4a428c896a33a0a5a326784e90122f77db4b4de2#diff-4b68f04ca203a03a3e475647b45d43111771e8b0bd2528eb7db64ada4f40fb9e

**Comment by joejulian** [comment]
Completed with #291
