### ISSUE TITLE
Run rpk command that creates ballast file

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#273]
The values.yaml file contains config options for the ballast file, but it looks like the following command needs to be ran in addition to having this config:

```
rpk redpanda tune ballast_file
```

See [this](https://github.com/redpanda-data/documentation/issues/1012) docs issue and [this](https://redpandacommunity.slack.com/archives/C01B3QBLUTT/p1673426060657539) community thread.

I set this as P2, but I may not be the right person to set priority on this (so feel free to update as appropriate).

**Comment by alejandroEsc** [comment]
Would a resolution of this be simply to document the need to do this? 

From what I remember of documentation tune must be run inside the kubernetes worker that is running the rp broker. That would mean we should probably update the docs, and probably update the install output if a ballast_file is set?

**Comment by JakeSCahill** [comment]
The current tuning doc doesn't take into account which storage volume is used. We just run the tuner on the worker node, so the ballast file gets created on the worker node at `/var/lib/redpanda/data/ballast`

**Comment by vuldin** [comment]
The current state causes confusion to users. They think they are enabling the ballast file by updating values.yaml but that's not the case. I think the best approach would be for us to create a ballast file in the helm chart.

**Comment by JakeSCahill** [comment]
Looks like this is a duplicate of https://github.com/redpanda-data/helm-charts/issues/233

**Comment by vuldin** [comment]
Ahh you are right, thanks @JakeSCahill (closing this).
