### ISSUE TITLE
Create multiple advertised listeners at once for each API

### ISSUE THREAD

**Issue by andrepoleza** [redpanda-data/helm-charts#276]
Hello! 😄 

I'm running a spike with the helm chart and trying to provision multiple advertised listeners for each API (e.g. plaintext (default) mode on Admin port (9644) **and** TLS listener on a different port), but as far as I understood it's not possible to express this type of configuration via [`listeners` property](https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/values.yaml#L422), only have each API with TLS enabled or not (so it's a all-or-nothing scenario). In the end I'd like to have, for each API:

- A port running Redpanda in plaintext mode
- Another port with TLS
- Another port with mTLS

I'm aware it's possible to do that via [listener configuration](https://docs.redpanda.com/docs/platform/cluster-administration/listener-configuration/) but it's not clear how exactly one can configure a local cluster (via minikube) to use the values on `redpanda:` section; am I missing something?

Thanks!

**Comment by joejulian** [comment]
This isn't possible with all apis. The admin api and, of course, the internal rpc server cannot be configured with multiple listeners: [node-properties](https://docs.redpanda.com/docs/reference/node-properties/#admin)

The kafka and pandaproxy listeners can be defined with multiple external entries now but the ability to configure tls separately will be in the first PR that I'm working on.

mTLS was never added to this chart. Support for that will be in a separate PR.
