### ISSUE TITLE
No resolvable bootstrap urls given in bootstrap.servers

### ISSUE THREAD

**Issue by vyom-soft** [redpanda-data/helm-charts#280]
Hello, I am very new to Redpanda.

I followed the instruction given here [RPA-K8-Helm](https://docs.redpanda.com/docs/get-started/quick-start/kubernetes-qs-dev/)

A existing Springboot Kafka client ( running in the same cluster where Redpanda kafka is) tries to connect and throws following err
In the application log 
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:730)
	... 28 common frames omitted

How & where is the bootstrap.servers configured. This is not mention in the document above. Can you please guide.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/18686082/213259413-372867c0-45f1-41c7-8d31-acc5142cfefa.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/18686082/213259711-c1fda49a-0cb1-44a5-b1ba-b993c7f0eba1.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/18686082/213264403-70a98a92-2593-43de-b604-add552481600.png">

**Comment by JakeSCahill** [comment]
Resolved in Slack: https://redpandacommunity.slack.com/archives/C01B3QBLUTT/p1674117291377679?thread_ts=1673960665.941799&channel=C01B3QBLUTT&message_ts=1674117291.377679
