### ISSUE TITLE
Support for managed connectors

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/helm-charts#293]
It would be great if the Helm chart could provision the managed connectors image: https://hub.docker.com/r/vectorized/connectors/tags.

PRD for Self-Managed connectors: https://docs.google.com/document/d/1C2I_O56wBPv2jlctN4VW2TOGf2AZfMuZ4oUbGWritBo/edit

**Comment by vladoschreiner** [comment]
This is a requirement for PNC.

**Comment by vladoschreiner** [comment]
@jrkinley shall we rename to "Support for self-managed connectors"?

**Comment by vladoschreiner** [comment]
Connectors image moved to https://hub.docker.com/r/redpandadata/connectors/

**Comment by alejandroEsc** [comment]
Additional Notes:

examples on how its done in terraform:

AWS: https://github.com/redpanda-data/cloudv2/blob/72d1663f77cd5bdc9610497b9dc2e39b0a98e8a8/terraform/provisioners/aws-redpanda-applications/main.tf#L39

GCP: https://github.com/redpanda-data/cloudv2/blob/72d1663f77cd5bdc9610497b9dc2e39b0a98e8a8/terraform/provisioners/gcp-redpanda-applications/main.tf#L87

Should help us come with a more accurate Estimate. 

The hope is this can be internal to the chart itself and not sub-charted.

**Comment by joejulian** [comment]
This should be its own chart. Redpanda should subchart it.

**Comment by mattschumpert** [comment]
Initial set of connectors for target customer: Mongo, HTTP source, JMS, IBM MQ

**Comment by mattschumpert** [comment]
More details @RafalKorepta . 

- This is running in a completely air gapped environment.
-Connectors will run in OpenShift, want to leverage k8s to scale connectors up and down, BUT the Redpanda cluster they interact with is on BARE METAL.  This means we must be able to deploy ONLY Redpanda Connectors to the K8s in a standalone way, without Redpanda itself

**Comment by alejandroEsc** [comment]
why was this closed?

**Comment by vladoschreiner** [comment]
As a duplicate of this https://github.com/redpanda-data/cloudv2/issues/7259
