### ISSUE TITLE
Add a check to fail if "soft" anti-affinity and external enabled

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#298]
With fixed NodePort ports, two pods cannot reside on the same node. If a user has external listeners enabled and sets the anti-affinity to soft, we should `fail`.

JIRA Link: [K8S-21](https://redpandadata.atlassian.net/browse/K8S-21)

[K8S-21]: https://redpandadata.atlassian.net/browse/K8S-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
