### ISSUE TITLE
helm chart config changes are not taken into account - easy fix

### ISSUE THREAD

**Issue by acristu** [redpanda-data/helm-charts#312]
Hello,

Is there a "hot reload" option for the config?
If not, then the helm chart should use a checksum annotation to restart pods when config changes: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments. I can provide a pull request if you agree with this change.

**Comment by RafalKorepta** [comment]
This issue was addressed by https://github.com/redpanda-data/helm-charts/pull/403.
