### ISSUE TITLE
Remove schema registry listener port

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#322]
The schema registry has a port defined for external listeners, but the schema registry service doesn't differentiate between internal and external clients (like the Kafka and HTTP services do). So this port is not needed, and all schema registry traffic can be routed to `listeners.schemaRegistry.port`.

**Comment by vuldin** [comment]
@joejulian mentioned that enabling TLS may be good reason why an additional port would be needed. This would assume there would be two schema registry ports accessible on a single Redpanda instance, and TLS would be enabled for only one of those ports.

I need to look more into whether it's possible to have two schema registry ports.

**Comment by joejulian** [comment]
So I think this means this issue should be closed, yes?
