### ISSUE TITLE
Improve release notes

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#329]
At the moment each release of the redpanda chart says the same thing: "Redpanda is the real-time engine for modern apps."

It would be better to give better details on what each release focuses on. Since each release is tied to a PR this could just pull in the PR's description.

JIRA Link: [K8S-24](https://redpandadata.atlassian.net/browse/K8S-24)

[K8S-24]: https://redpandadata.atlassian.net/browse/K8S-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
Use the flags in https://github.com/helm/chart-releaser

**Comment by alejandroEsc** [comment]
I will create a config file to account for certain actions like this we may want to take.
