### ISSUE TITLE
Console Deployment - Image registry.

### ISSUE THREAD

**Issue by surikbs** [redpanda-data/helm-charts#335]
Just Curious!! is it mandatory to pass the image registry variable in values.yaml for the console setup. 

While setting up the console via helm charts, the default image registry is not recognized while performing helm deploy.

![image](https://user-images.githubusercontent.com/19169786/218283081-7ecbd253-c2cd-4afc-b7c3-d805ec3f6da0.png)

if i pass image.registry as empty from the values file and the deployment ignores the default image registry configured on k8s.

![image](https://user-images.githubusercontent.com/19169786/218283239-39ad5054-5a64-4343-bb17-07bc8d31a47d.png)

i suggest to remove the image registry from the deployment file or it can be merged into a single variable for the image from the values file..

**Comment by alejandroEsc** [comment]
@surikbs thank you for the issue.
