### ISSUE TITLE
Clean up post-install and post-upgrade jobs

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#337]
Jobs can have a `ttlSecondsAfterFinished` that will automatically clean up jobs once they complete successfully. More details: https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

JIRA Link: [K8S-26](https://redpandadata.atlassian.net/browse/K8S-26)

[K8S-26]: https://redpandadata.atlassian.net/browse/K8S-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
There is a hook annotation we can add to do this for on-complete. Are you suggesting we add this?

**Comment by chrisseto** [comment]
Closing in favor of https://github.com/redpanda-data/helm-charts/issues/1021
