### ISSUE TITLE
[k8s] prefer gp3 as default disk in eks for redpanda for integrations

### ISSUE THREAD

**Issue by emaxerrno** [redpanda-data/helm-charts#357]
today redpanda defaults gp2. move default to gp3. 

JIRA Link: [K8S-28](https://redpandadata.atlassian.net/browse/K8S-28)

[K8S-28]: https://redpandadata.atlassian.net/browse/K8S-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
Unassinging until it's ready to be worked on.

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to reopen.
