### ISSUE TITLE
Improve `values.yaml` usability

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#359]
### What would you like to be added?

Today it isn't possible to consistently use a subset of the `values.yaml` file and expect that other values will use default values for sections of the file that are not defined. This is primarily due to the schema file, and an example is here: https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/values.schema.json#L967

This line requires this object to have a property when it may make sense to allow an empty object. Higher up, it may also make sense to allow not including an `external` object at all. More details on this in this conversation: https://github.com/redpanda-data/helm-charts/pull/320/files/b52be1eeb6e96de4020fb2d48a3a94b338e36bc6#r1114830767

### Why is this needed?

There are plenty of other examples that could be found, but the general idea is that a user can expect to look at the values.yaml as a guide, copy those specific parameters they want to modify from defaults, and use them in their own file for deploying how they need to without having to recreate the entire file just to change a few defaults (no matter how nested those default parameters may be in the file).

**Comment by alejandroEsc** [comment]
@vuldin could you give us an example of `it isn't possible to consistently use a subset of the values.yaml` The schema is important to validate away from bad values and help guide customers. It may be that we need to improve on these and that is what I am understanding so far.

**Comment by joejulian** [comment]
Is sounds like the use case your describing is done wrong. It sounds like someone is attempting to clone the helm-charts repo and edit the values.yaml file in the chart. This is not how helm works. Leave the values.yaml alone and override the subset of values in your own yaml file.

**Comment by alejandroEsc** [comment]
Closing this issue based on the description and discussion, please @vuldin if you disagree please re-open and we can take another stab at it.
