### ISSUE TITLE
Set environment variables

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#364]
### What would you like to be added?

Now that TLS is enabled by default, users must add additional flags to `rpk` commands.

It would be nice if the Helm chart automatically set environment variables such as:

- REDPANDA_ADMIN_TLS_TRUSTSTORE
- REDPANDA_API_ADMIN_ADDRS

### Why is this needed?

It makes users' lives easier and reduces the barrier to entry. Users won't run into errors because of missing flags.

JIRA Link: [K8S-30](https://redpandadata.atlassian.net/browse/K8S-30)

[K8S-30]: https://redpandadata.atlassian.net/browse/K8S-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
Helm doesn't have the ability to alter the user's environment. Are you suggesting this changes within the redpanda pods, or are you asking for them to be output as part of the install text that's output at the end (notes.txt)?

**Comment by RafalKorepta** [comment]
Can those environment variables be represented in Redpanda configuration file? If yes, then I wouldn't complicate our setup. 

P.S. [The 12-factor apps config explanation](https://12factor.net/config) as any config should be represented in env var might back fire in Redpanda vast configuration surface.

**Comment by JakeSCahill** [comment]
cc @r-vasquez

**Comment by r-vasquez** [comment]
Here is a table that lists command properties and their corresponding command line flags, environment variables, and configuration file settings: https://docs.redpanda.com/docs/get-started/intro-to-rpk/#specifying-command-properties

Maybe a good approach will be to set the rpk section of the redpanda.yaml with those values.

**Comment by RafalKorepta** [comment]
I see that redpanda.yaml can have set:
* instead of REDPANDA_ADMIN_TLS_TRUSTSTORE -> rpk.admin_api.tls.truststore_file 
* instead of REDPANDA_API_ADMIN_ADDRS -> rpk.admin_api.addresses
