### ISSUE TITLE
Remove set-datadir-ownership as it appears to no longer be necessary

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/helm-charts#370]
### What happened?

Our use of chown to fixup datadir directory ownership throws errors in Kubernetes environments where containers aren't allowed to run privileged. This is happening at least with Rancher/rke2.

```CreateContainerConfigError (container has runAsNonRoot and image will run as root (pod: "redpanada-0_redpanda(04835735-5d80-4d48-bad5-fa2cfbe6c39c)", container: set-datadir-ownership))

Which comes from this section 

        - name: set-datadir-ownership
          image: {{ .Values.statefulset.initContainerImage.repository }}:{{ .Values.statefulset.initContainerImage.tag }}
          command: ["/bin/sh", "-c", "chown {{ $uid }}:{{ $gid }} -R /var/lib/redpanda/data"]
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/redpanda/data
```

It appears that part of this was fixed up in https://github.com/redpanda-data/helm-charts/issues/173 but the chown was left around.

### What did you expect to happen?

Don't throw an error. This appears to be unnecessary given the runAsUser/runAsGroup/fsGroup support that got added previously.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

N/A. Requires a restricted K8s environment to replicate.

### Which are the affected charts?

Redpanda

### Chart Version(s)

2.12.0

### Cloud provider

N/A.

On-prem Rancher/rke2.

**Comment by alejandroEsc** [comment]
I believe you can set `.Values.statefulset.skipChown=true` (which not exactly my preferred approach to this) to ignore this initContainer and not have it run. Would that solve your issue?

**Comment by hcoyote** [comment]
It did. But that's not the purpose of this issue. If we no longer need to do this due to other changes in the helm chart, then we shouldn't keep this code in here for someone to stumble across.

**Comment by joejulian** [comment]
We should also consider setting `fsGroupChangePolicy: OnRootMismatch` as a default. Will save a lot of startup time on large production installs. As long as we allow it to be overridden, it's safe.
