### ISSUE TITLE
Use MetalLB to test external access

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#381]
### What would you like to be added?

LoadBalancer and NodePort external access should be tested with TLS across all services.

### Why is this needed?

This is needed ensure external access works as intended.

**Comment by RafalKorepta** [comment]
I would suggest to test in some cloud environment. The kind cluster would be hard to simulate node port for each Redpanda broker.

**Comment by joejulian** [comment]
With MetalLB it's pretty easy.
