### ISSUE TITLE
Enable prometheus scraping in `values.yaml`

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#389]
### What would you like to be added?

Add Prometheus annotations to Pods automatically by setting a value in the Helm chart. Something like `metrics.prometheus.enabled=true`.

### Why is this needed?

It's difficult and error-prone to get Prometheus monitoring working with our Helm chart. Users can add annotations to Pods in `statefulset.annotations`, but I couldn't get the Prometheus Helm chart to find the Pods and scrape the metrics: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations

If we had a well tested way of integrating with Prometheus, we could provide a switch to enable/disable Prometheus scraping.

**Comment by JakeSCahill** [comment]
I got it working with annotations. The steps are documented here: https://docs.redpanda.com/docs/manage/kubernetes/monitor/#configure-prometheus

**Comment by JakeSCahill** [comment]
I couldn't however get it to work with TLS enabled. It requires configuring `tls_config` for the Kubernetes Pods: https://github.com/prometheus-community/helm-charts/blob/3f829dc1814913ccad2f444ddfbb45c3e7c67bf5/charts/prometheus/values.yaml#L929

**Comment by joejulian** [comment]
Fixed by #498
