### ISSUE TITLE
Create testing process  for cloud storage settings [eks]

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#396]
We have no tests for the cloud storage settings. The azure keys were added, defaulting to empty strings. This broke gcp (and probably aws) storage because the azure settings too precedence. Redpanda treats empty strings as being set so it broke the whole cluster.

We need tests in each cloud to protect against regressions.

**Comment by joejulian** [comment]
Tasks created for spinning up EKS cluster and Buildkite config created but the AWS credentials are not in the environment. I've pinged @ivotron for help.

**Comment by ivotron** [comment]
which variables are needed? this is for the devprod aws account? can you please post a link to the code that references these?
