### ISSUE TITLE
After upgrade, access_point_uri is empty

### ISSUE THREAD

**Issue by travisdowns** [redpanda-data/helm-charts#405]
### What happened?

After an upgrade of my helm chart to 3.0.6 and Redpanda from 23.1.1 to 23.1.3, S3 cloud storage was not working.

Underlying cause is that the redpanda config `cloud_storage_api_endpoint` is an empty string rather than null. Redpanda treats this as a "set" URL and then uses the empty string instead of the default `s3.amazonaws...` URI and will fail to connect.

I initially deployed this cluster with helm and had done several helm upgrades without this issue. In the most recent upgrade I updated the helm chart to 3.0.6 and also the Redpanda version to v23.1.3 (from .1) when this issue occurred.

```
redpanda        redpanda        13              2023-03-25 03:28:03.054703601 +0000 UTC deployed        redpanda-3.0.6          v23.1.1
```

### What did you expect to happen?

Tiered storage to keep working.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Perhaps a helm upgrade with the newest helm chart will do it.

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
COMPUTED VALUES:
USER-SUPPLIED VALUES: null
auth:
  sasl:
    enabled: false
    mechanism: SCRAM-SHA-512
    secretRef: redpanda-users
    users:
    - mechanism: SCRAM-SHA-512
      name: admin
      password: change-me
clusterDomain: cluster.local
commonLabels: {}
config:
  cluster:
    retention_bytes: 461718750000
    retention_local_target_bytes_default: 39410000000
  node: {}
  tunable:
    compacted_log_segment_size: 67108864
    group_topic_partitions: 16
    kafka_batch_max_bytes: 1048576
    kafka_connection_rate_limit: 1000
    log_segment_size: 536900000
    log_segment_size_max: 536900000
    log_segment_size_min: 4096
    max_compacted_log_segment_size: 536870912
    topic_partitions_per_shard: 1000
console:
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  config: {}
  configmap:
    create: false
  console:
    config: {}
  deployment:
    create: false
  enabled: true
  extraContainers: {}
  extraEnv: []
  extraEnvFrom: []
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ""
  global: {}
  image:
    pullPolicy: IfNotPresent
    registry: docker.redpanda.com
    repository: vectorized/console
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 99
    runAsUser: 99
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources: {}
  secret:
    create: false
    enterprise: {}
    kafka: {}
    login:
      github: {}
      google: {}
      oidc: {}
      okta: {}
    redpanda:
      adminApi: {}
  secretMounts: []
  securityContext:
    runAsNonRoot: true
  service:
    annotations: {}
    port: 8080
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
external:
  addresses:
  - 192.168.12.68
  - 192.168.2.90
  - 192.168.23.204
  - 192.168.1.17
  - 192.168.28.159
  - 192.168.31.207
  - 192.168.5.141
  - 192.168.25.181
  - 192.168.29.76
  - 192.168.1.108
  - 192.168.13.100
  - 192.168.2.24
  - 192.168.27.162
  - 192.168.31.236
  - 192.168.19.174
  enabled: true
  type: NodePort
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: vectorized/redpanda
  tag: v23.1.3
license_key: <snip>
license_secret_ref: {}
listeners:
  admin:
    external:
      default:
        advertisedPorts:
        - 31644
    port: 9644
    tls:
      cert: default
      requireClientAuth: false
  http:
    enabled: true
    external:
      default:
        advertisedPorts:
        - 30082
        port: 8083
    kafkaEndpoint: default
    port: 8082
    tls:
      cert: default
      requireClientAuth: false
  kafka:
    external:
      default:
        advertisedPorts:
        - 31092
        port: 9094
    port: 9093
    tls:
      cert: default
      requireClientAuth: false
  rpc:
    port: 33145
    tls:
      cert: default
      requireClientAuth: false
  schemaRegistry:
    enabled: true
    external:
      default:
        advertisedPorts:
        - 30081
        port: 8084
    kafkaEndpoint: default
    port: 8081
    tls:
      cert: default
      requireClientAuth: false
logging:
  logLevel: info
  usageStats:
    enabled: true
nameOverride: ""
nodeSelector: {}
post_install_job:
  enabled: true
post_upgrade_job:
  enabled: true
rackAwareness:
  enabled: false
  nodeAnnotation: topology.kubernetes.io/zone
rbac:
  annotations: {}
  enabled: false
resources:
  cpu:
    cores: 15
    overprovisioned: false
  memory:
    container:
      max: 85Gi
    enable_memory_locking: false
serviceAccount:
  annotations: {}
  create: false
  name: ""
statefulset:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9644"
    prometheus.io/scrape: "true"
  budget:
    maxUnavailable: 1
  initContainerImage:
    repository: busybox
    tag: latest
  initContainers:
    configurator:
      resources: {}
    setTieredStorageCacheDirOwnership:
      resources: {}
    tuning:
      resources: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
  nodeSelector: {}
  podAffinity: {}
  podAntiAffinity:
    custom: {}
    topologyKey: kubernetes.io/hostname
    type: hard
    weight: 100
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
  replicas: 15
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
    runAsUser: 101
  skipChown: false
  startupProbe:
    failureThreshold: 120
    initialDelaySeconds: 1
    periodSeconds: 10
  tolerations: []
  topologySpreadConstraints:
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
storage:
  hostPath: ""
  persistentVolume:
    annotations: {}
    enabled: true
    labels: {}
    size: 12288Gi
    storageClass: local-path
  tieredConfig:
    cloud_storage_access_key: <snip>
    cloud_storage_api_endpoint: ""
    cloud_storage_azure_container: null
    cloud_storage_azure_shared_key: null
    cloud_storage_azure_storage_account: null
    cloud_storage_bucket: tdowns-full3
    cloud_storage_cache_size: 1650000000000
    cloud_storage_credentials_source: config_file
    cloud_storage_enable_remote_read: true
    cloud_storage_enable_remote_write: true
    cloud_storage_enabled: true
    cloud_storage_region: us-west-2
    cloud_storage_secret_key: <snip>
  tieredStorageHostPath: ""
  tieredStoragePersistentVolume:
    annotations: {}
    enabled: true
    labels: {}
    size: 1540Gi
    storageClass: local-path
tls:
  certs:
    default:
      caEnabled: true
  enabled: false
tolerations: []
tuning:
  tune_aio_events: true
```

There you can see the `cloud_storage_api_endpoint` set to `""`.

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
prometheus      prometheus      9               2023-03-24 01:37:08.907883896 +0000 UTC deployed        prometheus-20.0.1       v2.41.0    
redpanda        redpanda        13              2023-03-25 03:28:03.054703601 +0000 UTC deployed        redpanda-3.0.6          v23.1.1    
```

</details>

### Cloud provider

<details>
AWS
</details>

**Comment by jcsp** [comment]
The related ticket for making Redpanda more resistant to this type of thing is https://github.com/redpanda-data/redpanda/issues/9592.  Helm chart still needs updating to say "null" for unset nullable properties, rather than empty string: Redpanda will treat empty strings as validation errors for URLs once #9592 is done.

**Comment by alejandroEsc** [comment]
@jcsp this seems to be a general issue with how things are set/unset in the world of helm, there are several approaches we can take here, including just not adding things unless they are not set to empty. Can your team help us identify where/which of these configs should be applied in this fashion?

**Comment by joejulian** [comment]
```
# Optional cloud storage backend variant used to select API capabilities. If not supplied, will be inferred from other configuration parameters. (one of aws, google_s3_compat, azure, minio, unknown, restart required)
cloud_storage_backend:
```
Let's add this to the values and if `cloud_storage_enabled` is true, use the schema to require one of those. (except "restart required". Let's not give them that as a storage choice. :grin: )

That way it won't matter if there are empty strings for keys not being used, they won't be used.

**Comment by jcsp** [comment]
> @jcsp So these should be specifically the json value of null, not the string "null" nor the key being absent, correct?

Ideally, they should simply not be set at all.  Properties that are nullable (according to the schema at `/v1/cluster_config/schema` may be set to null, although this is not equivalent to not setting them (see the various slack threads about this for more)

> If a key has been set and is subsequently absent, will that key remain set in redpanda's internal configuration?

Presuming that by absent you mean absent from your call to PUT /v1/cluster_config, then yes.  Omitting a key does not reset it to default: you have to put it in the `remove` part of the request body to do that.

**Comment by joejulian** [comment]
> > If a key has been set and is subsequently absent, will that key remain set in redpanda's internal configuration?
> 
> Presuming that by absent you mean absent from your call to PUT /v1/cluster_config, then yes. Omitting a key does not reset it to default: you have to put it in the `remove` part of the request body to do that.

Since we use rpk and it doesn't do that for string types, I'm going to stick with my thought that requiring `cloud_storage_backend` if `cloud_storage_enabled` is true.

**Comment by travisdowns** [comment]
> Since we use rpk and it doesn't do that for string types, I'm going to stick with my thought that requiring cloud_storage_backend if cloud_storage_enabled is true.

This may just solve this specific problem, but isn't the mismatch here more general?

Is the idea of our helm chart that it always sets all the configuration values it knows about, either using a default value (from a file in this repo) or the user specified value?

**Comment by toddfarmer** [comment]
Need collaboration with cloud team - @sbocinec identified in meeting.

**Comment by joejulian** [comment]
We had many meetings about this. The conclusion is that the helm chart will filter all configuration keys to be absent if the value is empty or null. If there are fields we later require empty strings or the value null, we'll tackle those exceptions as they arise.

**Comment by travisdowns** [comment]
Will it actively remove keys (pass to the remove keys API) if they are in
this state, or simply not set them (leaving the previous set value, if any)?

**Comment by joejulian** [comment]
Helm has no way of knowing keys need to be passed to a remove api. The template will only include the keys that the user sets.

**Comment by RafalKorepta** [comment]
I hope rpk cluster config import will reconcile the yaml file generated by helm.

**Comment by joejulian** [comment]
That's what came out of the conversation. We'll do it as stated and if it doesn't work, we can see what's needed at that point.

**Comment by toddfarmer** [comment]
@RafalKorepta : I'm checking in on the status here - can you share an update? Thanks!

**Comment by RafalKorepta** [comment]
I'm trying to change helm chart, so that it will address https://vectorizedio.atlassian.net/wiki/spaces/DES/pages/354025481/Configuration+Handling+Guidelines.

The filtering and notification is my main concern. I don't know yet how to create automated tests.

I set next update on 19/04/2023
