### ISSUE TITLE
Add support for SI

### ISSUE THREAD

**Issue by rkruze** [redpanda-data/helm-charts#41]

**Comment by vuldin** [comment]
I've been focused on this, and I have the helm chart and tiered storage integrated (with most properties hard-coded for now). The next step is to ensure these properties can be modified by the user in the best way, then create a feature branch and PR.

I'll also include steps (similar to the excellent project from @patrickangeles https://github.com/patrickangeles/redpanda-si-demo) showing how to use tiered storage via the helm chart.

**Comment by RafalKorepta** [comment]
Done via https://github.com/redpanda-data/team-kubernetes-internal/issues/4
