### ISSUE TITLE
Allow console startup times to be configured

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#411]
### What would you like to be added?

Allow console deployments to configure the startup maxRetries, retryInterval, maxRetryInterval, and backoffMultiplier through the chart values.

### Why is this needed?

When the console pods are starting, if kafka isn't listening yet the pod will die and get restarted. This is normal expected behavior but this can alerts for failing pods in some monitoring configurations. Users would like to have this pod not fail during installation.

**Comment by RafalKorepta** [comment]
https://github.com/redpanda-data/console/blob/ed45e2e70780a4755018ecacfa99b6c98c674fb4/backend/pkg/config/kafka_startup.go#L18-L34
