### ISSUE TITLE
Test that Redpanda does receive SIGTERM on pod termination

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#437]
### What would you like to be added?

Add a test to ensure that redpanda is shutting down correctly. This can be tested by killing a pod with a long grace-period and checking that the elapsed time is less than the grace-period.

### Why is this needed?

We added a filter to redact secrets that were being output by redpanda logging. This filter used bash and bash does not pass signals to its child processes.

Redpanda has since been fixed to not leak that data and we now test to ensure only a patched release is being used and have removed bash. This test will prevent future regressions.

JIRA Link: [K8S-35](https://redpandadata.atlassian.net/browse/K8S-35)

[K8S-35]: https://redpandadata.atlassian.net/browse/K8S-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
There is no longer a bash wrapper around redpanda.
