### ISSUE TITLE
SASL Authentication failed

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#44]
I was able to go through the steps in methods 1 and 2 without issues. But when going through the steps outlined in [method 3](https://github.com/redpanda-data/helm-charts#method-3-tls-and-sasl-enabled) I run into the following error:
```sh
> kubectl -n redpanda run rpk -ti --rm --restart=Never --image vectorized/redpanda:v21.11.15 --command -- /bin/bash -c "rpk topic create test-topic --user admin --password test --sasl-mechanism SCRAM-SHA-256 --brokers redpanda-0.redpanda.redpanda.svc.cluster.local.:9092 --tls-enabled --tls-truststore <(echo '$CERT')"
unable to create topics [test-topic]: SASL authentication failed: security: Invalid credentials: SASL_AUTHENTICATION_FAILED: SASL Authentication failed.
```

Running the following command is successful:
```sh
> helm test redpanda -n redpanda
NAME: redpanda                                   
LAST DEPLOYED: Fri Apr 29 10:17:03 2022                                                            
NAMESPACE: redpanda                                                                                
STATUS: deployed                                                                                   
REVISION: 1             
TEST SUITE:     redpanda-test-kafka-sasl-status                                                    
Last Started:   Fri Apr 29 10:19:57 2022                                                           
Last Completed: Fri Apr 29 10:20:05 2022                                                           
Phase:          Succeeded
NOTES:
Congratulations on installing redpanda!
```

I'll look more into this, maybe the credentials aren't actually being enabled for SASL as the README says.

===========================

Adding more details on my environment:

System:
```
Ubuntu 22.04
Docker 20.10.12
```

Install arkade (my version was `v0.8.23`):
```
curl -sLS https://get.arkade.dev | sudo sh
```

```sh
> ark get helm jq minikube kubectl@v1.23.3 kubens kubectx
> minikube start --kubernetes-version v1.23.3
> ark install cert-manager
> helm install redpanda . -f values_add_tls.yaml -f values_add_sasl.yaml -n redpanda --create-namespace
> CERT=$(kubectl exec -n redpanda  redpanda-0 -c redpanda -- cat /etc/tls/certs/ca.crt)
> kubectl -n redpanda run rpk -ti --rm --restart=Never --image vectorized/redpanda:v21.11.15 --command -- /bin/bash -c "rpk topic create test-topic --user admin --password test --sasl-mechanism SCRAM-SHA-256 --brokers redpanda-0.redpanda.redpanda.svc.cluster.local.:9092 --tls-enabled --tls-truststore <(echo '$CERT')"
unable to create topics [test-topic]: SASL authentication failed: security: Invalid credentials: SASL_AUTHENTICATION_FAILED: SASL Authentication failed.
pod "rpk" deleted
pod redpanda/rpk terminated (Error)
```

Arkade installed `minikube@v1.25.2`, but that probably doesn't impact much since the commands above pin the k8s version.

**Comment by redp01** [comment]
This is because the admin user is registered in the config though needs explicitly creating via the rpk acl create command. The helm tests do create this user and then at the end of the test delete it. I will update the NOTES.txt to include the commands necessary and to avoid any confusion.

**Comment by vuldin** [comment]
> This is because the admin user is registered in the config though needs explicitly creating via the rpk acl create command. The helm tests do create this user and then at the end of the test delete it. I will update the NOTES.txt to include the commands necessary and to avoid any confusion.

Thanks for updating the README with this! I should have checked to see if the user was created, I assumed it had to be because the test was passing, but I didn't realize the test also created and then removed a user.

Just to point out that there is another PR waiting to be approved that also modifies the README, so you may branch from that to make it easy to merge both. It looks like Roko has approved/merged most PRs here, maybe @rkruze or @jrkinley could approve [this](https://github.com/redpanda-data/helm-charts/pull/45)?

**Comment by vuldin** [comment]
After creating the user (thanks @redp01 !) I was able to run through this test with the following commands:
```
k create ns helm-test
helm -n helm-test install redpanda redpanda -f redpanda/values_add_sasl.yaml -f redpanda/values_add_tls.yaml
CERT=$(k exec -n helm-test redpanda-0 -c redpanda -- cat /etc/tls/certs/ca.crt)
k exec -it -n helm-test redpanda-0 -- rpk acl user create admin -p test --api-urls redpanda.helm-test.svc.cluster.local:9644 --admin-api-tls-truststore /etc/tls/certs/admin/ca.crt --tls-truststore /etc/tls/certs/ca.crt
k -n helm-test run rpk -ti --rm --restart=Never --image vectorized/redpanda:v21.11.16 --command -- /bin/bash -c "rpk topic create test-topic --user admin --password test --sasl-mechanism SCRAM-SHA-256 --brokers redpanda-0.redpanda.helm-test.svc.cluster.local.:9092 --tls-enabled --tls-truststore <(echo '$CERT')"
```
