### ISSUE TITLE
Allow changing superuser SASL user password

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#459]
### What would you like to be added?

We are able to create a SASL user and set their password within `values.yaml`, but we cannot update this password in `values.yaml` for it then update the user's password.

### Why is this needed?

This behavior is expected since the password is listed in `values.yaml`

**Comment by alejandroEsc** [comment]
@vuldin suggested we do this via a sequence of events. 

```
rpk acl user delete admin
```

and 

```
rpk acl user create admin -p password --mechanism SCRAM-SHA-512
```

This will mean each time we pass through creation we should also pass through this sequence.

**Comment by joejulian** [comment]
Won't this result in excessive controller-log growth?

**Comment by alejandroEsc** [comment]
It would not, as this isn't something that is being "watched" and "updated" continuously. That will be something we need to trigger for in the future though.

**Comment by joejulian** [comment]
This will fix https://github.com/redpanda-data/helm-charts/issues/483

**Comment by joejulian** [comment]
Per conversation: in a sidecar shell script, use `inotifywait` in a loop and run the rpk commands to update redpanda when the secret mount changes.
