### ISSUE TITLE
Use secrets for SASL username/password and license

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#484]
### What would you like to be added?

Today SASL users are added into values.yaml directly, along with the Redpanda license. SASL users (both username/password) and the license should be provided to redpanda by referencing a secret in values.yaml, and the helm chart handles retrieving, decoding, and then providing it to redpanda.

### Why is this needed?

CI/CD pipelines use infra-as-code and will not include sensitive data.

**Comment by joejulian** [comment]
SASL users are added via a secret ref.

**Comment by vuldin** [comment]
Ahh, and I think license already has it too! https://github.com/redpanda-data/helm-charts/blob/14dcb9dd3a36e09ab21ae99ac21d32ddcf41e681/charts/redpanda/values.yaml#L64

I will test out both but I think this ticket may unneeded. Thanks @joejulian
