### ISSUE TITLE
Create testing process for cloud storage settings [gke]

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#489]
We have no tests for the cloud storage settings. The azure keys were added, defaulting to empty strings. This broke gcp (and probably aws) storage because the azure settings too precedence. Redpanda treats empty strings as being set so it broke the whole cluster.

We need tests in each cloud to protect against regressions.

Follow-on issue for #396

**Comment by RafalKorepta** [comment]
- [x] https://github.com/redpanda-data/helm-charts/pull/517

It's done.

Results can be found in nightly builds from main branch https://buildkite.com/redpanda/helm-charts/builds?branch=main
