### ISSUE TITLE
Create testing process for cloud storage settings [aks]

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#490]
We have no tests for the cloud storage settings. The azure keys were added, defaulting to empty strings. This broke gcp (and probably aws) storage because the azure settings too precedence. Redpanda treats empty strings as being set so it broke the whole cluster.

We need tests in each cloud to protect against regressions.

Follow-on issue for #396

**Comment by RafalKorepta** [comment]
Create service account using azure cli https://learn.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

**Comment by RafalKorepta** [comment]
Ivo and Tucker helped me with assigning owner role to service account.

**Comment by RafalKorepta** [comment]
By default `clusterctl generate cluster` was creating unmanaged Kubernetes cluster configuration. 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/79915e46f5366e0a38a6356318f3493b524f6e26/templates/cluster-template.yaml

If we would like to switch to AKS there is another template that needs to be adopted in https://github.com/redpanda-data/helm-charts/blob/f17650ed295da3e82aa9945e53b3e53e533a6500/.buildkite/capi/aks-cluster/templates/aks.yaml

REF:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/79915e46f5366e0a38a6356318f3493b524f6e26/templates/cluster-template-aks.yaml
