### ISSUE TITLE
Location of technical service bulletin 2023-01.

### ISSUE THREAD

**Issue by jorianvo** [redpanda-data/helm-charts#523]
### What happened?

I'm trying to deploy `redpanda` to a cluster and I receive the following error message:
```
 Error: Failed to render chart: exit status 1: Error: execution error at (redpanda/templates/statefulset.yaml:60:28): 
  Error: Cannot do a rolling restart to enable or disable tls at the RPC layer: changing listeners.rpc.tls.enabled (redpanda.yaml:repdanda.rpc_server_tls.enabled) from false to true
  ***WARNING The following instructions will result in a short period of downtime.
  To accept this risk, run the upgrade again adding `--set force=true` and do the following:
  While helm is upgrading the release, manually delete ALL the pods:
      kubectl -n infra delete pod -l app.kubernetes.io/component=redpanda-statefulset
  If you got here thinking rpc tls was already enabled, see technical service bulletin 2023-01.
```
As the message already mentions, I got there thinking RPC TLS was already enabled 😉 

I'm happy to run the commands provided, that is not the problem. 
My question is: I'm trying to find the **technical service bulletin 2023-01** it mentions, but I can't seem to find anything?

### What did you expect to happen?

I was expecting to find the **technical service bulletin 2023-01** somewhere explaining the issue.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Not relevant.

### Anything else we need to know?

No.

### Which are the affected charts?

Redpanda

### Chart Version(s)

| CHART  | APP VERSION |
| ------------- | ------------- |
| redpanda-4.0.22 | v23.1.10  |

### Cloud provider

Not relevant.

JIRA Link: [K8S-41](https://redpandadata.atlassian.net/browse/K8S-41)

[K8S-41]: https://redpandadata.atlassian.net/browse/K8S-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
Thank you for reporting this, we are aware of that and there was some discussion about making those available, at the meantime you can probably ask the community chat for information as we try to see where we landed on this.

**Comment by joejulian** [comment]
cc @JakeSCahill

**Comment by JakeSCahill** [comment]
@mattschumpert was this TSB made public anywhere?

**Comment by mattschumpert** [comment]
The TSB is at minimum published in our customer support system here:n https://support.redpanda.com/hc/en-us/articles/14136781776407-TSB-2023-01-RPC-TLS-Settings-Not-Correctly-Applied. That requires registration.

cc @tmgstevens if there's a public location.

**Comment by c4milo** [comment]
I landed here wondering about the same. It would help to find the bulletin if the logs print out the URL.

**Comment by chrisseto** [comment]
23.1 is no longer supported and a link has been published in this issue. We'll ensure the future TSBs have a URL associated with them if/when logging warnings.
