### ISSUE TITLE
Request template for initContainers

### ISSUE THREAD

**Issue by Boniker** [redpanda-data/helm-charts#533]
### What happened?

In case if we have self-managed kafka cluster signed by self-signed certificate, we need to add this certificate to trusted.

For it we have the next folder `/etc/ssl/certs/ca-certificates.crt ` where locates all the trusted certificate.
In this case we don't have any initContainer for adding this cert to trusted. It will be fine to implement it.

### What did you expect to happen?

Adding new configs and possibilities to helm chart

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Something like this can be possible:

```
{{- if .Values.initContainers }}
initContainers:
{{- range .Values.initContainers }}
- name: {{ .name }}
  image: "{{ .image }}:{{ .tag }}" -> can be possible to set the same image as running under `redpandadata/console`
  imagePullPolicy: {{ .imagePullPolicy }}
  command: {{ .command }}
  args:
  {{ toYaml .args | indent 10 }}

  {{- if .configmap }}
  envFrom:
  - configMapRef:
      name: {{ .name }}
  {{- end }}

  {{- if .volumeMounts }}
  volumeMounts:
  {{- range .volumeMounts }}
  - name: {{ .name }}
    mountPath: {{ .mountPath }}
  {{- if .subPath }}
    subPath: {{ .subPath }}
  {{- end }}
  {{- if .readOnly }}
    readOnly: {{ .readOnly }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
```

### Anything else we need to know?

```
values:
  initContainers: []
```

### Which are the affected charts?

Console

### Chart Version(s)

Using the latest one: `0.6.4`

### Cloud provider

<details>

- AWS

</details>

**Comment by alejandroEsc** [comment]
You wish to allow to change the image for the init container, is this what you are saying? Just want to be clear and that I am not missing something with the certificates.

**Comment by Boniker** [comment]
Yes, you can add the ability to change the command for the main container.
But, as for me, the best solution would be
- create a volume, for example, an empty dir
- mount it to the init container (perform some manipulations inside the init container)
- mount the volume from the init container to the main container to avoid unnecessary files in the main container.

How does this relate to certificates?
We have a broker with a self-signed certificate and we need to add it to the trusted ones. If I add it to `/etc/ssl/certs/ca-certificates.crt`, I can continue to work with my kafka cluster over SSL.

**Comment by joejulian** [comment]
We should add industry standard "extraVolumes" and "extraInitContainers" values.

**Comment by Boniker** [comment]
@joejulian, any updates until now?

**Comment by Boniker** [comment]
@alejandroEsc but you did that for chart redpanda. My request was for chart: console. Please, do it!?

**Comment by alejandroEsc** [comment]
> @alejandroEsc but you did that for chart redpanda. My request was for chart: console. Please, do it!?

Oh I am so sorry, there was an ask for this and i thought this was a duplicate ticket for redpanda chart. Will do!

**Comment by alejandroEsc** [comment]
console has extraVolumes and extraVolumeMounts in the values file, so not adding those, but will add the ability to add your own init containers.

**Comment by Boniker** [comment]
That's what I'm asking for. Thanks. Waiting =))

**Comment by Boniker** [comment]
Thanks, working fine.
