### ISSUE TITLE
How to add spec.metadata.labels?

### ISSUE THREAD

**Issue by jarlva** [redpanda-data/helm-charts#538]
Hi, I need to add istio injection to the statefulset by using the following last line. I tried inserting into the statefullset section but the chart ignores it. How can I do that?

```apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
```

**Comment by joejulian** [comment]
You can add the labels through `commonLabels`

**Comment by jarlva** [comment]
Thank you.
