### ISSUE TITLE
Fix nightly CI tests

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#542]

**Comment by RafalKorepta** [comment]
https://github.com/redpanda-data/helm-charts/pull/544

**Comment by RafalKorepta** [comment]
- [x] https://github.com/redpanda-data/helm-charts/pull/547
- [x] https://github.com/redpanda-data/helm-charts/pull/550
- [x] https://github.com/redpanda-data/helm-charts/pull/544
- [ ] https://github.com/redpanda-data/helm-charts/pull/553
