### ISSUE TITLE
Allow helm-chart to deploy a custom io-config.yaml for self-managed k8s installs

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/helm-charts#551]
### What would you like to be added?

Today, rpk handles deploying an io-config.yaml on a user's behalf for known instance types in cloud.

For self-managed installs on baremetal using the helm-chart on k8s, there's no direct way to insert an io-config.yaml generated by rpk iotune. 

User would like to have a way for the helm chart to support doing this natively.

Right now, user has patched configmap.yaml to create the io-config.yaml and the statefulset.yaml to deploy the file when redpanda.yaml and bootstrap.yaml are setup.

### Why is this needed?

Allow use of custom io-config.yaml generated by rpk iotune on baremetal servers where the user has done the iotune testing themselves.

@joejulian has an idea for a better way to do this than laying out the file according to what the user provided us in a diff screenshot.

**Comment by alejandroEsc** [comment]
Do we know what the better idea is so we can record it here?

**Comment by joejulian** [comment]
We should just add an `additionalVolumes` map.

**Comment by joejulian** [comment]
@alejandroEsc I think this can be closed by #676. Might need to work with @JakeSCahill to get this specific need documented though.

**Comment by joejulian** [comment]
@JakeSCahill The documentation for this would be how to generate io-config.yaml, create a configmap from the io-config.yaml file, and how to add that configmap as an additionalVolume to the statefulset.
