### ISSUE TITLE
Cannot use helm values file to enable `console.config.connect`

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#556]
From a customer:

> Found another bug in Console Helm Chart. Helm values console.config is not taken into account as the element is evaluated internally. Hence I cannot use Helm values to enable console.config.connect. https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/console/configmap.yaml#L66

**Comment by ethanttbui** [comment]
@vuldin I am facing this issue as well. Do you suggest any temporary workaround?
I am not very familiar with Helm. 😢

**Comment by joejulian** [comment]
The workaround would be to set `console.enabled=false` in the redpanda chart and to install the console chart separately.

**Comment by joejulian** [comment]
Just to make sure I understand the expectation here, what is the goal of setting `redpanda.console.config.connect`?

**Comment by ethanttbui** [comment]
@joejulian for my case, I simply want to enable connect view on RedPanda Console
