### ISSUE TITLE
Please add a tailing dot to the default internal hostnames in order to avoid a cert's hostname mismatch

### ISSUE THREAD

**Issue by masapanda** [redpanda-data/helm-charts#575]
### What happened?

When a TLS was enabled, and internal broker hostnames were as follows;

```
BROKERS
=======
ID    HOST                                             PORT
0*    redpanda-0.redpanda.redpanda.svc.cluster.local.  9093
1     redpanda-1.redpanda.redpanda.svc.cluster.local.  9093
2     redpanda-2.redpanda.redpanda.svc.cluster.local.  9093
```
An application returned the following error,

`Caused by: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot`

This was because the default server cert didn't contain DNS names with a tailing dot in the server cert.
```
DNS:redpanda-cluster.redpanda.redpanda.svc.cluster.local,
DNS:*.redpanda-cluster.redpanda.redpanda.svc.cluster.local,
DNS:redpanda.redpanda.svc.cluster.local,
DNS:*.redpanda.redpanda.svc.cluster.local,
```

Though hostnames without a tailing dot works for curl, openssl, or many applications, some applications like this example may require including a tailing dot hostname in DNS names. 

### What did you expect to happen?

A server cert should include hostname with a tailing dot in DNS section. 

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

1. Deploy Redpanda
<details>

```console
$ helm install redpanda redpanda/redpanda -n redpanda --create-namespace
```
</details>
2. Confirm a default internal broker hostname with a tailing dot
<details>

```console
$  kubectl exec -it -n redpanda  redpanda-0 -c redpanda -- rpk  --brokers redpanda-0.redpanda.redpanda.svc.cluster.local:9093 --tls-truststore /etc/tls/certs/default/ca.crt --tls-enabled cluster info

CLUSTER 
=======
redpanda.1b21c3f3-60e9-46ab-8076-5a3f709c1c10

BROKERS
=======
ID    HOST                                             PORT
0*    redpanda-0.redpanda.redpanda.svc.cluster.local.  9093
1     redpanda-1.redpanda.redpanda.svc.cluster.local.  9093
2     redpanda-2.redpanda.redpanda.svc.cluster.local.  9093
```
</details>

3. Confirm a server cert does not have DNS host names with a tailing dot

<details>

```console
$  k get secret redpanda-default-cert -n redpanda -o json | jq -r '.data."tls.crt"' | base64 -d | openssl x509 - -text -noout | grep DNS | grep DNS | sed -e 's/,/,\n/g' | grep -oP '\S+cluster.local.*$'
DNS:redpanda-cluster.redpanda.redpanda.svc.cluster.local,
DNS:*.redpanda-cluster.redpanda.redpanda.svc.cluster.local,
DNS:redpanda.redpanda.svc.cluster.local,
DNS:*.redpanda.redpanda.svc.cluster.local,
```
</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm list -n redpanda
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART          	APP VERSION
redpanda	redpanda 	1       	2023-07-03 11:29:38.924762 -0700 PDT	deployed	redpanda-4.0.51	v23.1.13
```

</details>

### Cloud provider

<details>
Azure
</details>

**Comment by joejulian** [comment]
Please confirm that the JDK being used does not have this bug: https://bugs.openjdk.org/browse/JDK-8065422

**Comment by joejulian** [comment]
Adding a trailing dot to the certificate is not best practice.
