### ISSUE TITLE
Use the upstream MetalLB Helm chart

### ISSUE THREAD

**Issue by oskapt** [redpanda-data/helm-charts#58]
Instead of using the downstream Bitnami chart, we can use the upstream/origin MetalLB chart. Instructions are [here](https://metallb.org/installation/#installation-with-helm).

This also lets us simply point to MetalLB's documentation for installation via Helm, Kustomize or manifest instead of duplicating that information here.

**Comment by redp01** [comment]
@vuldin - this will be simpler to implement once #56 is merged.

**Comment by redp01** [comment]
@vuldin - this will be simpler to implement once #56 is merged.

**Comment by joejulian** [comment]
This falls outside the scope of this chart. MetalLB or kube-vip could be mentioned in documentation if needed. As of this point, the redpanda chart does not intend to support LoadBalancer service types. This will be carefully documented to explain why.
