### ISSUE TITLE
default_topic_replications says it's ignored, but isn't. Default should be 3.

### ISSUE THREAD

**Issue by solsson** [redpanda-data/helm-charts#583]
### What happened?

A three replica cluster was created with default_topic_replications = 1

### What did you expect to happen?

A default that's less prone to data being unavailable during maintenance, or documentation that recommends an override

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

run with values
```
statefulset:
  replicas: 3
```

Then `rpk cluster --api-urls redpanda:9644 config get default_topic_replications`

### Anything else we need to know?

It's unclear how the above sections at https://github.com/redpanda-data/helm-charts/blob/redpanda-4.0.53/charts/redpanda/values.yaml#L891 can be used to set this.

### Which are the affected charts?

Redpanda

### Chart Version(s)

4.0.53

### Cloud provider

<details>

</details>

**Comment by solsson** [comment]
To anyone else who wants to set this config, using `tunable` and _not_ `node` seems to work. Under `node` it has no effect, which means the un-indent under that section in values.yaml means undefined section.

```
config:
  tunable:
    default_topic_replications: 3
```

**Comment by joejulian** [comment]
blocked on #678 and #679
