### ISSUE TITLE
Cluster-wide unreadiness makes operations harder

### ISSUE THREAD

**Issue by solsson** [redpanda-data/helm-charts#584]
### What happened?

After 40s of downtime for a single broker, all pods in the replicaset go unready.

### What did you expect to happen?

I would expect a health check that indicates health per pod, to aid alerting and troubleshooting. Furthermore given such a probe, a service _without_ `publishNotReadyAddresses` could be used for admin API traffic and possibly client bootstrap to avoid hitting a less healthy replica or a replica on a temporarily troubled node.

I suppose this is a matter of opinion. However, if the only reason for ["It's ok that this cluster-wide check affects all the pods"](https://github.com/redpanda-data/helm-charts/blob/redpanda-4.0.53/charts/redpanda/templates/statefulset.yaml#L258) is the PodDisruptionBudget, I'd like to point out that with max unavailable 1 it will prevent "roll any pods" just as well if only the unhealthy pod went unready.

In operations seeing this result from `get pods` is quite frightening, but everything might actually be fine. Maybe redpanda-2 started up slowly for example because it triggered node scale-up.
<img width="393" alt="image" src="https://github.com/redpanda-data/helm-charts/assets/144945/21a48297-21cc-4110-9be3-4d9a8923939d">

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

values:

```
statefulset:
  replicas: 3
```

`kubectl scale --replicas=2 statefulset redpanda && sleep 40 && kubectl scale --replicas=3 statefulset redpanda`

### Which are the affected charts?

Redpanda

### Chart Version(s)

4.0.53

### Cloud provider

<details>

</details>

**Comment by joejulian** [comment]
It's not just for PDB. Redpanda's health is determined at the cluster level so a leaderless or underreplicated topic, for example, needs to prevent any pod from being rolled or you would lose availability or maybe data.

In the example you bring up, if the health check just can't reach the admin API, then only that pod will show not-ready.

**Comment by solsson** [comment]
> a leaderless or underreplicated topic, for example, needs to prevent any pod from being rolled or you would lose availability or maybe data

Good point. I have no better suggestion on how to achieve this behavior using k8s primitives than to use readiness + PDB.

> health check just can't reach the admin API, then only that pod will show not-ready

In other words startup and liveness should be on the pod level while readiness is on the cluster level? I don't think the current implementation meets this spec though, because all probes use the service DNS name. It's my understanding that they'll hit any pod. Did you consider using `localhost`?

**Comment by joejulian** [comment]
> > health check just can't reach the admin API, then only that pod will show not-ready
> 
> In other words startup and liveness should be on the pod level while readiness is on the cluster level, and the readiness check should use the pod's endpoint? I don't think the current implementation meets this spec though, because all probes use the service DNS name. It's my understanding that they'll hit any pod. Did you consider using `localhost`?

It does use the local admin api:
https://github.com/redpanda-data/helm-charts/blob/08a901dd9008a848553109bd1b43f23ecac6acb3/charts/redpanda/templates/_helpers.tpl#L362-L364

The SERVICE_NAME environment variable is the pod name:
https://github.com/redpanda-data/helm-charts/blob/08a901dd9008a848553109bd1b43f23ecac6acb3/charts/redpanda/templates/statefulset.yaml#L128-L132

We don't use localhost because localhost isn't in the tls certificate.

**Comment by solsson** [comment]
Thank you for the explanation. I misunderstood the naming of the env.

**Comment by joejulian** [comment]
Yeah, I inherited the env name. :man_shrugging: . One of the two hardest problems in computer science: naming things, cache invalidation, and off-by-one errors.
