### ISSUE TITLE
Remove ability to set non-container properties

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#59]
Some config properties have values that would never work in a container environment. A couple of examples:
- `tune_cpu`
- `tune_disk_irq`

These properties should not be included in `values.yaml`, and if detected they should either 1) be ignored or 2) block startup of the cluster (and print a useful error message).

If the default values for these props are not what is needed for a container environment, then these props should have their values hard-coded to the correct value.

JIRA Link: [K8S-3](https://redpandadata.atlassian.net/browse/K8S-3)

[K8S-3]: https://redpandadata.atlassian.net/browse/K8S-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
This can be handled with the json schema. Blocked for #164

**Comment by alejandroEsc** [comment]
i thought this was completed already? Is this to further add items or keep them from being added?

**Comment by joejulian** [comment]
This would be to add rules to the schema to prevent setting those two keys.
