### ISSUE TITLE
add `logFilter` top-level parameter

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#62]
`logFilter` will be used to appropriately populate `logger-log-level` argument. One resource with further info from Daria on slack: https://runbooks.dev.vectorized.cloud/howtos/redpanda/redpanda-log-levels/

Another option from Ben via slack: `--logger-log-level=kafka=debug:kafka/client=debug`

JIRA Link: [K8S-4](https://redpandadata.atlassian.net/browse/K8S-4)

[K8S-4]: https://redpandadata.atlassian.net/browse/K8S-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vuldin** [comment]
More details around the available loggers:
```
> redpanda --help-loggers
...
INFO   redpanda::main - application.cc:162 - Redpanda v22.1.3 - d1a4e00a30a11a2e5898f5a8bac80097d2864c8b
INFO   redpanda::main - application.cc:170 - kernel=5.15.0-27-generic, nodename=redpanda-0, machine=x86_64
Available loggers:
    admin_api_server
    archival
    archival-ctrl
    assert
    cloud_storage
    cluster
    compaction_ctrl
    compression
    coproc
    dns_resolver
    exception
    fault_injector
    group-metadata-migration
    http
    httpd
    io
    json
    kafka
    kafka/client
    kvstore
    metrics-reporter
    offset_translator
    pandaproxy
    r/heartbeat
    raft
    redpanda::main
    request_auth
    rpc
    s3
    scheduler
    scollectd
    seastar
    seastar_memory
    security
    serde
    storage
    storage-gc
    syschecks
    tx
```

I've seen posts from people saying they've enabled the following:
```
kafka
kafka/client
security
k/groups
storage
storage-gc
cloud_storage
archival
```

One option is that we could assume the user would only ever care about certain loggers, and allow them to set logging to `debug`, `info`, `trace`, etc. with something like this in `values.yaml`:
```
logging: "debug"
```

Then we add an argument to `spec.template.spec.containers[0].args` in `statefulset.yaml`:
```
--logger-log-level=kafka=debug:kafka/client=debug:security=debug:k/groups=debug:storage=debug:storage-gc=debug:cloud_storage=debug:archival=debug
```

Another option to give the user the option to choose which subsystems they want to view more details on, which would make the helm chart more capable at the expense of complixity.

**Comment by vuldin** [comment]
Once we figure out which way to go, we need to update this doc with details: https://github.com/redpanda-data/runbooks/blob/main/content/howtos/redpanda/redpanda-log-levels.md

**Comment by chrisseto** [comment]
Closing in favor of https://github.com/redpanda-data/helm-charts/issues/1171
