### ISSUE TITLE
Support customize redpanda service name

### ISSUE THREAD

**Issue by sniperking1234** [redpanda-data/helm-charts#644]
### What would you like to be added?

I would like the internal access address within Kubernetes to be configured as `kafka-0.kafka-headless.common.svc.cluster.local:9092`, but currently, it can only be configured as `kafka-0.kafka.common.svc.cluster.local:9092`.

### Why is this needed?

I previously installed Kafka using the chart package from https://github.com/bitnami/charts/tree/main/bitnami/kafka. The access address after installation is as mentioned above. I would like other applications to seamlessly migrate to Redpanda without needing to modify the access address.

**Comment by joejulian** [comment]
Seems reasonable. Do you think this is something you might be interested in contributing?

**Comment by sniperking1234** [comment]
I will give it a try.

**Comment by RafalKorepta** [comment]
achieved in https://github.com/redpanda-data/helm-charts/pull/674

Thank you @sniperking1234
