### ISSUE TITLE
Add mTLS

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#65]
See for details https://docs.redpanda.com/docs/security/kubernetes-mtls/

**Comment by vuldin** [comment]
Adding open issues that block this feature:
- https://github.com/redpanda-data/helm-charts/issues/835
- https://github.com/redpanda-data/helm-charts/issues/848
- https://github.com/redpanda-data/helm-charts/issues/849
- https://github.com/redpanda-data/helm-charts/issues/855
- https://github.com/redpanda-data/helm-charts/issues/857

Related docs PR: https://github.com/redpanda-data/docs/pull/99

**Comment by chrisseto** [comment]
Closing in favor of https://github.com/redpanda-data/helm-charts/issues/1195
