### ISSUE TITLE
Improve secret managment

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#67]
Secrets at the moment are hard-coded, and helm is configured to delete all created resources (including secrets).

- add "keep" helm resource policy to secrets
- look into auto-generating secret value

More details here: https://itnext.io/manage-auto-generated-secrets-in-your-helm-charts-5aee48ba6918

**Comment by vuldin** [comment]
- Annotation here https://github.com/redpanda-data/helm-charts/blob/main/redpanda/templates/certs.yaml#L10
- auto-generate secret here https://github.com/redpanda-data/helm-charts/blob/main/redpanda/templates/certs.yaml#L7

**Comment by vuldin** [comment]
This should also allow making use of existing secrets.

**Comment by joejulian** [comment]
fixed in #122 

Secrets are now created by and owned by cert-manager or the user.
