### ISSUE TITLE
Docker rate limit issues

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/helm-charts#685]
### What would you like to be added?

The latest helm charts uses [docker.redpanda.com](http://docker.redpanda.com/) as registry url which is neat but it causes docker rate limit issues even for people who have paid docker hub since the url is not a docker hub url. Using [docker.io/redpandadata/redpanda:v23.2.3](http://docker.io/redpandadata/redpanda:v23.2.3) solves the problem.

### Why is this needed?

Avoid Docker pull rate limits.

**Comment by joejulian** [comment]
You can follow https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ to and use the same credentials, just log in to docker.redpanda.com with your docker credentials.

**Comment by joejulian** [comment]
Closing this as done.
