### ISSUE TITLE
Statefulset template code refers to non-existent parameter

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#693]
### What happened?

`.Values.resources.memory.min` doesn't exist, but the statefulset template will do something if it is found: https://github.com/redpanda-data/helm-charts/blob/4aaa90b0bca357586649a8dceb5bf19f0b272ba9/charts/redpanda/templates/statefulset.yaml#L350C23-L354

### What did you expect to happen?

Expected this code block to not exist.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

JIRA Link: [K8S-56](https://redpandadata.atlassian.net/browse/K8S-56)

[K8S-56]: https://redpandadata.atlassian.net/browse/K8S-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vuldin** [comment]
There are two options:
1. remove the code block from the statefulset template
2. add the parameters to the values.yaml schema, and possibly also to values.yaml with a comment/description

**Comment by chrisseto** [comment]
This appears to have been handled. Please re-open if that's not the case.
