### ISSUE TITLE
Kafka endpoint is hard-coded to POD_ID in `_helpers.tpl`

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#70]
The kafka endpoint can be set in `values.yaml` but this doesn't overwrite the `redpanda.kafka.internal.listen.port` template defined in `_helpers.tpl`.

https://github.com/redpanda-data/helm-charts/blob/f4411f2f9a8b60d6cdd524182595284c08323c3c/redpanda/templates/_helpers.tpl#L74-L76

**Comment by vuldin** [comment]
Not sure if this is an issue, since $POD_ID is an environment variable passed to the container. Look more into this.

**Comment by joejulian** [comment]
This is working as intended.
