### ISSUE TITLE
template `redpanda.kafka.external.listen.port` points to non-existent external port parameter

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#71]
While refactoring `values.yaml` I found that a recent commit added `config.redpanda.kafka_api[].external.port` (or `listeners.kafka[].external.port`. The issue is `config.redpanda.kafka_api[]` (or `listeners.kafka[]`) is a list of potential listeners, so instead a new listener should be added to this list with the appropriate port.

**Comment by vuldin** [comment]
Adressing this ticket should also include looking into the template `redpanda.kafka.external.listen.port` to see where and how it's used. This template will need to be changed to either point to the appropriate external listener or removed.

**Comment by joejulian** [comment]
fixed in #122
