### ISSUE TITLE
default values should be set in the values.yaml

### ISSUE THREAD

**Issue by joejulian** [redpanda-data/helm-charts#716]
We shouldn't specify what the default is in a comment, here, we should put the default in the values file.

https://github.com/redpanda-data/helm-charts/blob/48adf16fba072315d0c6923fbca37b5bf599cb1d/charts/redpanda/values.yaml#L730-L731

JIRA Link: [K8S-58](https://redpandadata.atlassian.net/browse/K8S-58)

[K8S-58]: https://redpandadata.atlassian.net/browse/K8S-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
The comment should say something like 'default is "sasl" if left empty' but yeah i see your point.

**Comment by joejulian** [comment]
No, the value `sasl` should be in the values file. Principal of least surprise. Don't make hidden defaults.

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to reopen.

**Comment by RafalKorepta** [comment]
I reopend it and then I realised we have weird contract with Redpanda. I agree with @joejulian `Principal of least surprise`, but Redpanda want's to have power to handle missing `authenticationMethod` (the default) property. Any logic in the config input should not be changed by helm chart.
