### ISSUE TITLE
fullname vs name in Redpanda helm chart

### ISSUE THREAD

**Issue by lalithsuresh** [redpanda-data/helm-charts#727]
### What happened?

The Redpanda helm chart currently assigns `redpanda.fullname` as the name for the created StatefulSet.

`redpanda.fullname` is currently rendered as either fullnameOverride or release-name as of now. It does not make use of `redpanda.name` (e.g., via `printf "%s-%s" .Release.Name $name`):

```
{{- define "redpanda.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

I'm using Redpanda as a dependency in a Helm chart that brings up several services. But due to the above rendering, the StatefulSet and pods from the Redpanda chart show up with the top-level chart's release name (the stateful set is `release-name` and the pods are `release-name-0`...). That makes it hard to tell apart the redpanda resources from the top-level chart's own resources.

### What did you expect to happen?

I was hoping to only set `redpanda.nameOverride=foo` in my chart's `values.yaml` and have the Redpanda StatefulSets and pods show up as something like `release-name-foo` instead.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm template ./redpanda --set nameOverride="foo"

<snip>
Source: redpanda/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name # <------- does not use $name, could be release-name-$name perhaps.
  labels:
    app.kubernetes.io/component: foo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: foo
    helm.sh/chart: redpanda-5.4.2
<snip>
```

</details>

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

I noticed it first on 2.6.1, but this is also on the latest chart and current main.

</details>

### Cloud provider

NA

**Comment by alejandroEsc** [comment]
Just out of curiosity, is the use of the fullnameOverride not an option for your naming needs?

**Comment by lalithsuresh** [comment]
@alejandroEsc I'd like to use this Helm chart as a dependency in another Helm chart. I'm not sure it's possible to set fullnameOverride according to a template, as it is exposed via values.yml.

**Comment by RafalKorepta** [comment]
@lalithsuresh 

Given you are using Redpanda chart as a dependency you should be able to use fullname value to change the names of the Pods.

As a example that full name that changes only redpanda resources is working.
https://github.com/RafalKorepta/helm-dependnecy-example

**Comment by alejandroEsc** [comment]
> @lalithsuresh
> 
> Given you are using Redpanda chart as a dependency you should be able to use fullname value to change the names of the Pods.
> 
> As a example that full name that changes only redpanda resources is working. https://github.com/RafalKorepta/helm-dependnecy-example
> 
> Can you set `nameOfTheDependnecy.fullnameOverride` where `nameOfTheDependnecy` placeholder is defined in Chart.yaml like [in the example](https://github.com/RafalKorepta/helm-dependnecy-example/blob/c5dcab138b29e47e4a28884f529bb27d7b404f5c/redpanda-dep/Chart.yaml#L27)?

Please review previous comments.

**Comment by joejulian** [comment]
@lalithsuresh we're hesitant to change this for a couple reasons.

1. there's a ton of prior art for doing it the way we're currently doing it. Now I'm not one that does thing only because that's the way they've always been done, but I do like to have compelling reasons. I'm not sure that "it's named for the release" is compelling. It's supposed to be. The subchart resources _are_ part of the parent chart. Further, you can use label filtering to reduce any confusion.
2. The biggest reason to avoid this is that changing the naming convention would change the resource names for everyone that's already using the chart, breaking all the users. Obviously that would be bad.

Can you think of some other way to handle this that would satisfy your wishes, doesn't break prior-art, and definitely does not break existing installations?

**Comment by lalithsuresh** [comment]
Thanks for investigating this. I don't see an easy way for you to fix this without breaking existing installations either.

Using the Redpanda Operator and creating a templated Cluster CR from within my Helm chart might solve my problem.
