### ISSUE TITLE
Dedicated cache disk handling

### ISSUE THREAD

**Issue by dotnwat** [redpanda-data/helm-charts#764]
### What would you like to be added?

When cloud cache and partition data share a single device, the amount of space assigned to each may be expressed as two percentages that add to 100% of the unreserved disk space https://docs.redpanda.com/current/manage/cluster-maintenance/disk-utilization/#space-management.

When a dedicated cloud cache device is used then the entire disk may be used (e.g. setting cloud storage cache size percent to 100%). In the dedicated drive setup, the disk reservation percentage still applied to both cache and data disks.

### Why is this needed?

DIfferent configurations for different scenarios.

JIRA Link: [K8S-60](https://redpandadata.atlassian.net/browse/K8S-60)

[K8S-60]: https://redpandadata.atlassian.net/browse/K8S-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to reopen.
