### ISSUE TITLE
Compatibility with Kubernetes v1.20.2

### ISSUE THREAD

**Issue by emahdij** [redpanda-data/helm-charts#769]
### What would you like to be added?

Hello,

I am currently running a Kubernetes cluster on version v1.20.2 and am interested in deploying Redpanda using the provided Helm charts. I was wondering if there is a specific version of the Redpanda Helm chart that is compatible with Kubernetes v1.20.2. If so, could you please provide the version number?

Thank you for your assistance.

Best regards

### Why is this needed?

To avoid any compatibility issues that might arise from using a non-compatible version of the Helm chart.

**Comment by alejandroEsc** [comment]
@emahdij, please look at: https://github.com/redpanda-data/helm-charts#requirements 

We currently support 1.21.0

But we might change this soon. Ill ask the team and update as needed.
