### ISSUE TITLE
How to add other plugins to Redpanda Connector?

### ISSUE THREAD

**Issue by stenneepro** [redpanda-data/helm-charts#778]
### What would you like to be added?

It would be great if Redpanda Connector supports to add other plugins using Helm chart configuration.
Or something like `initContainer`

### Why is this needed?

I tried to install MongoDB Kafka Connector.
I investigated the chart, but can't find solution.
I tried to upload JAR files to Connector pod, but it says permission denied.

Why can't we make it easy?
Here is example.
https://artifacthub.io/packages/helm/licenseware/kafka-connect

As you can see, it's really easy to install plugins.

**Comment by stenneepro** [comment]
I have enabled connector via setting `connector.enabled=true`
But can't find a way to install necessary plugins.

**Comment by RafalKorepta** [comment]
Currently I can only say that you can create your own docker image as described https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/docker-image/#install-new-connector-type

**Comment by stenneepro** [comment]
@RafalKorepta 
I was able to deploy Redpanda Connectors with custom plugins using `redpanda-connectors` helm chart.

1. First set connector.enabled=false in Redpanda helm chart.
https://artifacthub.io/packages/helm/redpanda-data/redpanda
2. Install Redpanda Connector using Redpanda Connectors helm chart.
https://artifacthub.io/packages/helm/redpanda-data/connectors
3. Add custom plugins to Redpanda Connectors using volume mount.

**Comment by RafalKorepta** [comment]
Thank you @stenneepro. It would be awesome to contribute with new values.yaml definition.

**Comment by joejulian** [comment]
I'm glad you were able to find the solution!
