### ISSUE TITLE
Update the PVC size if the values change

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#779]
### What would you like to be added?

Today users expect that if they update the volume size within the helm or operator, that this will be reflected in the running pods. But instead this only updates the statefulset so that newly rolled out pods will make use of the change (but the rollout isn't done as part of the update). This is documented [here](https://docs.redpanda.com/current/manage/kubernetes/storage/resize-persistentvolumes/#expand-persistentvolumes-that-use-dynamic-provisioners).

### Why is this needed?

Adding this feature would make the behavior more closely match expectations when updating volume size.

JIRA Link: [K8S-63](https://redpandadata.atlassian.net/browse/K8S-63)

[K8S-63]: https://redpandadata.atlassian.net/browse/K8S-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alejandroEsc** [comment]
Did we test this before documenting?

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to reopen.

I would also consider this out of scope of a helm chart. We can look into adding this to the operator post defluxing.
