### ISSUE TITLE
Add top-level `networkPolicy` parameter

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#78]
```yaml
# Network policy
networkPolicy: {}
```
See https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L839

JIRA Link: [K8S-7](https://redpandadata.atlassian.net/browse/K8S-7)

[K8S-7]: https://redpandadata.atlassian.net/browse/K8S-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
