### ISSUE TITLE
configurator secret name is not set using the redpanda.fullname named template which prevents installing multiple helm releases

### ISSUE THREAD

**Issue by anapsix** [redpanda-data/helm-charts#790]
### What happened?

The configurator [secret name](https://github.com/redpanda-data/helm-charts/blob/redpanda-5.6.8/charts/redpanda/templates/secrets.yaml#L278) is not set  using the `redpanda.fullname` named template, but the `redpanda.name` instead, which prevents installing multiple instances of different releases of Redpanda Helm chart.
Any additional `helm install` results in the error: 
```
Error: Unable to continue with install: Secret "redpanda-configurator" in namespace "<namespace>" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "two": current value is "one"
```
Where "one" and "two" are release names.

### What did you expect to happen?

I've expected to be able to install multiple instances / releases of Redpanda Helm chart into the same namespace, as was possible before at some point, before "configurator" secret was introduced.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>
$ helm install one redpanda/redpanda --version "5.6.8"
$ helm install two redpanda/redpanda --version "5.6.8"
</details>

### Anything else we need to know?

Using `nameOverride` can be used as a workaround,

```
$ helm install one redpanda/redpanda --set nameOverride one --version 5.6.8
$ helm install two redpanda/redpanda --set nameOverride two --version 5.6.8
```

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm ls
NAME          	NAMESPACE   	REVISION	UPDATED                              	STATUS  	CHART         	APP VERSION
one		default		2       	2023-10-13 00:31:57.519999 +0200 CEST	deployed	redpanda-5.6.8	v23.2.9
```

</details>

### Cloud provider

<details>
should not matter, as the same happens in Minikube, EKS, or any other K8s env
</details>

**Comment by alejandroEsc** [comment]
May need to rewrite the match label for the pdb as part of this work.
