### ISSUE TITLE
rpk runs slowly on wsl. It takes about 5 seconds for the ordinary help option to display the command.

### ISSUE THREAD

**Issue by 1057105012** [redpanda-data/helm-charts#852]
### What happened?

rpk --help on wsl ubuntu

### What did you expect to happen?

rpk --help on wsl ubuntu exec less than 1 seconds

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

rpk --help on wsl ubuntu

### Which are the affected charts?

Redpanda

### Chart Version(s)

laster

### Cloud provider

laster

**Comment by 1057105012** [comment]
I'm not sure if rpk needs to access the network and then times out? Because I'm running it offline

**Comment by chrisseto** [comment]
Please re-open this issue on the [Redpanda repository](https://github.com/redpanda-data/redpanda) (Home of `rpk`) if you're still experiencing issues.
