### ISSUE TITLE
No way to set `kafka_mtls_principal_mapping_rules` in the values

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#855]
### What happened?

When using mTLS authentication, Redpanda allows the option to define mapping rules in `kafka_mtls_principal_mapping_rules`. See https://docs.redpanda.com/current/manage/security/authentication/#configure-mtls-with-authentication

This option doesn't seem to be supported in the chart. It's always set to `null`.

### What did you expect to happen?

We should have the option to set mapping rules in the Helm values.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by alejandroEsc** [comment]
Done. Tested and now config works as expected.
