### ISSUE TITLE
Integrate VPC PrivateLink

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#87]
See the following links for more details:
- https://aws.amazon.com/privatelink/?privatelink-blogs.sort-by=item.additionalFields.createdDate&privatelink-blogs.sort-order=desc
- https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html
- https://docs.aws.amazon.com/vpc/latest/privatelink/concepts.html

Need to investigate what changes to the listeners would be needed.

JIRA Link: [K8S-8](https://redpandadata.atlassian.net/browse/K8S-8)

[K8S-8]: https://redpandadata.atlassian.net/browse/K8S-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
No chart changes are needed. We just need a how-to document.

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
