### ISSUE TITLE
Investigate using host daemonset for Redpanda tuning

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#88]
Most Redpanda tuning available through `rpk` is not available on containers. Investigate a host-based daemonset that can tune hosts in a kubernetes cluster and report back details to the cluster.

JIRA Link: [K8S-9](https://redpandadata.atlassian.net/browse/K8S-9)

[K8S-9]: https://redpandadata.atlassian.net/browse/K8S-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
> Most Redpanda tuning available through rpk is not available on containers.
They can, they just need the correct security context set. This could be managed in init containers.

**Comment by chrisseto** [comment]
Closing due to age and inactivity. Feel free to re-open.
