### ISSUE TITLE
Docker registry in a not standard port

### ISSUE THREAD

**Issue by gbraes** [redpanda-data/helm-charts#895]
Hi,
   I am using a internal registry to pull the redpanda images.  I have changed my custom values.yaml with a  `image.registry` that is not in the standard port  `myregistry:4000/redpanda` . In any k8s manifest is not a problem but when I install redpanda helm chart It is giving the next error:
```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
redpanda:
- image.repository: Does not match pattern '^[a-z0-9-_/.]+$'
- image.tag: Does not match pattern '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$|^$'
```
 Any idea on how to overcome this error?

**Comment by joejulian** [comment]
A quick workaround is to disable schema validation: `--disable-openapi-validation`.
You should match the tag when moving the image to your private repo. This is easier to maintain over time.

The chart schema will need changed to accept the port specification.

**Comment by gspadotto** [comment]
I am facing the exact same issue. The problem, I suppose, is here: 
https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/values.schema.json#L336

There is no ":" in the regular expression, so it seems you cannot specify a port. 

I think this use case is discussed here: 
https://github.com/helm/helm/issues/10398

Were you able to overcome this?
