### ISSUE TITLE
Verify memory/core count is correct

### ISSUE THREAD

**Issue by rkruze** [redpanda-data/helm-charts#9]
We should verify that enough memory is made available for the cores given. If it is not we should provide an error. We should also check to make sure full cores are used and not partial cores. 

JIRA Link: [K8S-1](https://redpandadata.atlassian.net/browse/K8S-1)

[K8S-1]: https://redpandadata.atlassian.net/browse/K8S-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
There's no way for the helm chart to ensure there are enough nodes with enough resources to satisfy the Kubernetes scheduler.

What advantage do we gain from validating that only full cores are allocated? If you specify one full core but the application uses 4 cores, you'll still spend 75% of your time suspended. Cgroups work on utilization over time and suspend once a quota is hit before the end of a timer. I'm not sure this buys us anything.

**Comment by rkruze** [comment]
The original issue was not worded all that well, it should have been focused on saying that we should make sure 2GB of memory is allocated for each core, as this is our recommendation. 

Also for full cores, with our thread per core architecture and pinning to cores, using full cores seems to make sense but I'm not certain this is needed.

**Comment by chrisseto** [comment]
Closing due to age and lack of activity.
