### ISSUE TITLE
Redpanda on local kubernates cluster

### ISSUE THREAD

**Issue by bharathreddy901** [redpanda-data/helm-charts#902]
### What happened?

Hi Everyone - I am trying to deploy Redpanda on local Kubernates cluster(without internet), I am getting below error, Please check.

Error: values don't meet the specifications of the schema(s) in the following chart(s):
redpanda:
- image.tag: Does not match pattern '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$|^$'
![image (6)](https://github.com/redpanda-data/helm-charts/assets/96808632/34625079-f19a-4a0f-9d8a-a57b479fd995)
![image (5)](https://github.com/redpanda-data/helm-charts/assets/96808632/750a7609-bff7-492a-b505-fa90ed04bcd5)

### What did you expect to happen?

Hi Everyone - I am trying to deploy Redpanda on local Kubernates cluster(without internet), I am getting below error, Please check.

Error: values don't meet the specifications of the schema(s) in the following chart(s):
redpanda:
- image.tag: Does not match pattern '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$|^$'

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Anything else we need to know?

Please let me know how to resolve this issue?

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by joejulian** [comment]
If you're not going to match the original tag (a bad idea imho), you'll need to disable spec validation, `--disable-openapi-validation`.

**Comment by alejandroEsc** [comment]
i think you can also get around this by making a valid semver that is expecting something like v1.0.0 i think would work.
