### ISSUE TITLE
Review minimum required K8s version

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#911]
### What would you like to be added?

The minimum required K8s version necessary to run our Helm charts should be available in the `Chart.yaml`.

### Why is this needed?

We currently publish 1.21.0-0 but we recently discussed that this is not tested:

https://github.com/redpanda-data/helm-charts/blob/cc959498a40307a6fc6a6862a5174a960a7c1e0c/charts/redpanda/Chart.yaml#L35

We should test K8s versions and publish the minimum required `kubeVersion` that we are confident will work.

JIRA Link: [K8S-82](https://redpandadata.atlassian.net/browse/K8S-82)

[K8S-82]: https://redpandadata.atlassian.net/browse/K8S-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by joejulian** [comment]
kubeVersion is intended to declare what version of the kubernetes API is required. There are ways to lint this without doing a full test suite.

**Comment by david-yu** [comment]
Going to close this, as we tested against 1.25.x recently.
