### ISSUE TITLE
connectors helm fields not applying from operator

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#912]
### What happened?

I added additional helm values for the "connectors" sub-chart installed using the operator, but seems other then "enabled", nothing is applying to the actual generated helm release.

### What did you expect to happen?

I expected the operator to install the helm release with the provided values applied on the connectors sub-chart
Specifically these fields:
- monitoring
- volume
- volumeMounts

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-512
        secretRef: kafka-credentials
        users: []
    connectors:
      enabled: true
      monitoring:
        enabled: false
      storage:
        volume:
          - name: plugins
            persistentVolumeClaim:
              claimName: plugins-redpanda-connectors-redpanda
        volumeMounts:
          - mountPath: /opt/kafka/connect-plugins
            name: plugins
            readOnly: false
```
Generated helm release values are (note the missing connectors fields):
```
auth:
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    secretRef: kafka-credentials
connectors:
  enabled: true
```
</details>

### Anything else we need to know?

Initially trying to deploy this yaml gave me an error that I was adding non-existing fields, but after updating the CRDs it seems to have fixed this, but the fields are still not applying

### Which are the affected charts?

Redpanda, Operator, Connectors

### Chart Version(s)

<details>

```console
redpanda - 5.6.57
operator - 0.4.6
```

</details>

### Cloud provider

<details>
Linode
</details>

**Comment by alejandroEsc** [comment]
This is complete, should be fixed in the next release

**Comment by Aransh** [comment]
Thanks @alejandroEsc this does seem to fix this.
The values are now applied to the chart, but seems I'm getting another issue with the additional volumes, see https://github.com/redpanda-data/helm-charts/issues/940
