### ISSUE TITLE
RedPanda >= 5.6.59 broken podmonitors RBAC

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#927]
### What happened?

I have noticed my redpanda operator was failing to upgrade the redpanda chart since version 5.6.59 was released (through 5.6.60 as well).
Looking at the "HelmRelease" resource status, I see the following message:
```
        Helm upgrade failed: Unable to continue with update: could not get
        information about the resource PodMonitor "redpanda-connectors" in
        namespace "redpanda": podmonitors.monitoring.coreos.com
        "redpanda-connectors" is forbidden: User
        "system:serviceaccount:redpanda:redpanda-operator-qa" cannot get
        resource "podmonitors" in API group "monitoring.coreos.com" in the
        namespace "redpanda"


        Last Helm logs:


        preparing upgrade for redpanda

        resetting values to the chart's original version

        performing update for redpanda
```

### What did you expect to happen?

I expected the role created by the chart to include the relevant resources so install will not fail

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-512
        secretRef: kafka-credentials
        users: []
    connectors:
      enabled: true
      monitoring:
        enabled: true
    monitoring:
      enabled: true
```

</details>

### Anything else we need to know?

While on my main cluster I'm seeing this issue for upgrading from 5.6.58 to 5.6.60, on my secondary cluster I'm seeing an issue upgrading from 5.6.45 to 5.6.60.
On the HelmRelease status I see:
```
  lastAppliedRevision: 5.6.45
  lastAttemptedRevision: 5.6.60 
```
But the error here is different:
```
        Helm upgrade failed: another operation (install/upgrade/rollback) is in
        progress


        Last Helm logs:


        preparing upgrade for redpanda
```

Trying to run "helm ls -n redpanda -a" shows this:
```
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS         	CHART          	APP VERSION
redpanda	redpanda 	12      	2023-11-16 03:10:08.495331719 +0000 UTC	pending-upgrade	redpanda-5.6.47	v23.2.15
```

Which seems to imply redpanda tried to upgrade to version 5.6.47, failed, and is stuck ever since, blocking the operator from attempting addition upgardes.
I'm not sure if this is related, or requires an additional issue, please let me know how I should proceed, and if there is any way to manually debug this.

### Which are the affected charts?

Redpanda, Operator

### Chart Version(s)

<details>

```console
operator - 0.4.8
redpanda - described above
```

</details>

### Cloud provider

<details>
Linode
</details>

**Comment by alejandroEsc** [comment]
This is an issue with a missing role for the operator. PR created to take care of this. I have tested this and it works as expected.
