### ISSUE TITLE
Remove environment variables from templates

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#94]
Environment variables are being returned as values from templates. This is an issue if these templates get used in any place other than within the statefulset config, since that the pods being setup within the statefulset are the only place where the environment variables are available. These templates should return proper values, and then can be used throughout the helm chart as expected.

**Comment by joejulian** [comment]
This may be fixed in #122

**Comment by joejulian** [comment]
This doesn't seem to be an issue to me. Please reopen if it's still valid.
