### ISSUE TITLE
No "secretRef" option for tiered-storage credentials

### ISSUE THREAD

**Issue by Aransh** [redpanda-data/helm-charts#960]
### What happened?

I was trying to configure tiered-storage, when I noticed the chart requires me to provide the access/secret keys as part of the helm values, which is a big security issue for us (not to mention the fact it complicates GitOps).

### What did you expect to happen?

I expected there to be an option to provide a "secretRef" to a kubernetes secret containing the credentials (which I can then manage securely), same as there is for SASL, or for the enterprise license.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

Nothing to reproduce

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
redpanda chart version - 5.7.5
```

</details>

### Cloud provider

<details>
Linode
</details>

**Comment by RafalKorepta** [comment]
@Aransh I will implement Secret Reference, but I would like to suggest that you use IAM role to authenticate and authorize access to S3 bucket.

Please see section named
```
To configure access to an S3 bucket with an IAM role:
```
in
https://docs.redpanda.com/current/manage/tiered-storage/#configure-object-storage

The important part is (https://docs.redpanda.com/current/manage/security/iam-roles/#configuring-iam-roles)
```
cloud_storage_credentials_source: sts
```

**Comment by Aransh** [comment]
@RafalKorepta Thank you for the suggestion, but we are not using AWS here.
We are using Linode, which has an s3-compatible object storage service, but no IAM (access/secret key only)

**Comment by Aransh** [comment]
Thanks @RafalKorepta, will try to out
Any chance to add the access key this way too?

Our current flow is:
1. Create access key and push it to secret manager (via terraform)
2. Use operator to create k8s secrets from secret manager secrets
3. Use secretRefs to point to the pre-existing secrets

This is very GitOps friendly, and simplifies the process of deploying new clusters, or replacing the access key without having to manually copy the credentials and paste them in the actual values.
