### ISSUE TITLE
Make `service.discovery.yaml` ports list dynamic

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#97]
![image](https://user-images.githubusercontent.com/310946/174791994-865f5252-60d5-4872-9994-75b55d5688da.png)

**Comment by vuldin** [comment]
Apparently this service is created only to ensure appropriate DNS entries are created:
https://github.com/redpanda-data/helm-charts/blob/main/redpanda/templates/service.discovery.yaml#L18-#L20

But if this service is only for DNS as the comment suggests, then why worry about setting up ports at all? I'll hard-code these ports to the first in the list, removing the templates in the process. This will allow me to continue to cleanup the templates, and I'll leave this ticket open to investigate more broadly why this service is needed.

**Comment by joejulian** [comment]
fixed in #122
