### ISSUE TITLE
Make redpanda-cluster service ports dynamic

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#98]
![image](https://user-images.githubusercontent.com/310946/174792561-772a92a9-9aa0-4c2e-ad86-4e617d51c1fe.png)

**Comment by vuldin** [comment]
https://github.com/redpanda-data/helm-charts/blob/899400cd9fdbed3ea398d7db6d1ff78856c2bcc0/redpanda/templates/services.cluster.yaml#L37

**Comment by vuldin** [comment]
This is a bug since they user could define a port correctly in `values.yaml` but it still wouldn't work as expected if the listener where the port is defined isn't the first in the list.

**Comment by joejulian** [comment]
fixed in #122
